import 'server-only';

import type {
  SamiIntegrationProviderDefinition,
} from '@/lib/integrations/types';

export const APP_RUNTIME_INTEGRATION_PROVIDERS:
  SamiIntegrationProviderDefinition[] = [
    {
      key:'accounting_bank_feed',
      name:'Accounting Bank Feed',
      description:'Receive verified normalized bank, cash or mobile-money transactions from a bank, aggregator or provider bridge and import them into Accounting.',
      category:'finance',
      iconKey:'landmark',
      connectionType:'webhook',
      websiteUrl:null,
      docsUrl:null,
      capabilities:['inbound_webhook','automation_triggers'],
      moduleKey:'accounting',
    },
    {
      key:'accounting_document_extractor',
      name:'Accounting Document Extractor',
      description:'Receive verified OCR/document extraction results for private Accounting documents, including PDFs handled by an external provider bridge.',
      category:'finance',
      iconKey:'scan-line',
      connectionType:'webhook',
      websiteUrl:null,
      docsUrl:null,
      capabilities:['inbound_webhook','automation_triggers'],
      moduleKey:'accounting',
    },
    {
      key:'invoicing_payment_gateway',
      name:'Invoice Payment Gateway',
      description:'Receive verified normalized payment events from a gateway or provider bridge and settle SaMi invoices automatically.',
      category:'commerce',
      iconKey:'credit-card',
      connectionType:'webhook',
      websiteUrl:null,
      docsUrl:null,
      capabilities:['inbound_webhook','automation_triggers'],
      moduleKey:'invoicing',
    },
    {
      key:'invoicing_payment_pesapal',
      name:'Pesapal Invoice Payments',
      description:'SaMi-managed Pesapal invoice payment connection with verified IPN settlement.',
      category:'commerce',
      iconKey:'credit-card',
      connectionType:'webhook',
      websiteUrl:'https://www.pesapal.com',
      docsUrl:'https://developer.pesapal.com',
      capabilities:['inbound_webhook','automation_triggers'],
      moduleKey:'invoicing',
    },
    {
      key:'invoicing_payment_mpesa',
      name:'M-PESA Invoice Payments',
      description:'SaMi-managed M-PESA invoice payment connection with verified callback settlement.',
      category:'commerce',
      iconKey:'credit-card',
      connectionType:'webhook',
      websiteUrl:'https://developer.safaricom.co.ke',
      docsUrl:'https://developer.safaricom.co.ke',
      capabilities:['inbound_webhook','automation_triggers'],
      moduleKey:'invoicing',
    },
    {
      key:'invoicing_payment_stripe',
      name:'Stripe Invoice Payments',
      description:'SaMi-managed Stripe invoice payment connection with verified webhook settlement.',
      category:'commerce',
      iconKey:'credit-card',
      connectionType:'webhook',
      websiteUrl:'https://stripe.com',
      docsUrl:'https://docs.stripe.com',
      capabilities:['inbound_webhook','automation_triggers'],
      moduleKey:'invoicing',
    },
    {
      key:'invoicing_payment_paystack',
      name:'Paystack Invoice Payments',
      description:'SaMi-managed Paystack invoice payment connection with verified webhook settlement.',
      category:'commerce',
      iconKey:'credit-card',
      connectionType:'webhook',
      websiteUrl:'https://paystack.com',
      docsUrl:'https://paystack.com/docs',
      capabilities:['inbound_webhook','automation_triggers'],
      moduleKey:'invoicing',
    },
    {
      key:'invoicing_payment_flutterwave',
      name:'Flutterwave Invoice Payments',
      description:'SaMi-managed Flutterwave invoice payment connection with verified webhook settlement.',
      category:'commerce',
      iconKey:'credit-card',
      connectionType:'webhook',
      websiteUrl:'https://flutterwave.com',
      docsUrl:'https://developer.flutterwave.com',
      capabilities:['inbound_webhook','automation_triggers'],
      moduleKey:'invoicing',
    },
    {
      key:'invoicing_payment_paypal',
      name:'PayPal Invoice Payments',
      description:'SaMi-managed PayPal invoice payment connection with verified webhook settlement.',
      category:'commerce',
      iconKey:'credit-card',
      connectionType:'webhook',
      websiteUrl:'https://www.paypal.com',
      docsUrl:'https://developer.paypal.com/docs',
      capabilities:['inbound_webhook','automation_triggers'],
      moduleKey:'invoicing',
    },
  ];
