export type SamiAppArchetype =
  | 'analytics'
  | 'board'
  | 'calendar'
  | 'canvas'
  | 'catalog'
  | 'compliance'
  | 'document'
  | 'inbox'
  | 'ledger'
  | 'library'
  | 'map'
  | 'operations'
  | 'people'
  | 'pipeline'
  | 'pos'
  | 'service';

export type SamiAppHeader =
  | 'command'
  | 'editor'
  | 'immersive'
  | 'quiet'
  | 'split';

export type SamiAppDensity =
  | 'compact'
  | 'balanced'
  | 'spacious';

export type SamiAppNavigation =
  | 'minimal'
  | 'pills'
  | 'rail'
  | 'tabs';

export type SamiAppContentWidth =
  | 'wide'
  | 'full'
  | 'focused';

export type SamiAppUiProfile = {
  moduleKey: string;
  eyebrow: string;
  headline: string;
  archetype: SamiAppArchetype;
  header: SamiAppHeader;
  density: SamiAppDensity;
  navigation: SamiAppNavigation;
  contentWidth: SamiAppContentWidth;
  accent: string;
  secondary: string;
  signature: string;
};

/*
 * Every first-party SaMi business application owns an explicit visual
 * identity. This is intentionally not a category-to-theme lookup.
 *
 * Shared primitives may be reused, but the composition profile for each app
 * is declared independently so CRM does not silently become "purple Sales",
 * Accounting does not become "finance Inventory", and operational apps can
 * use the interaction model that best matches their work.
 */
export const SAMI_APP_UI_PROFILES:
  Record<string, SamiAppUiProfile> = {
  "accounting": {
    moduleKey: "accounting",
    eyebrow: "General Ledger",
    headline: "Close books with confidence",
    archetype: "ledger",
    header: "quiet",
    density: "compact",
    navigation: "rail",
    contentWidth: "wide",
    accent: "#2563eb",
    secondary: "#4f46e5",
    signature: "Journal-first financial workspace with period controls, reconciliation emphasis and audit-ready density.",
  },
  "invoicing": {
    moduleKey: "invoicing",
    eyebrow: "Receivables Studio",
    headline: "Invoice, collect and reconcile",
    archetype: "document",
    header: "immersive",
    density: "balanced",
    navigation: "tabs",
    contentWidth: "wide",
    accent: "#0f766e",
    secondary: "#14b8a6",
    signature: "Document-led receivables workspace focused on customer balances, payment progress and polished invoice work.",
  },
  "expenses": {
    moduleKey: "expenses",
    eyebrow: "Expense Desk",
    headline: "Capture, approve and reimburse",
    archetype: "service",
    header: "quiet",
    density: "balanced",
    navigation: "pills",
    contentWidth: "wide",
    accent: "#b45309",
    secondary: "#f59e0b",
    signature: "Fast receipt and report workflow with approval queues and reimbursement status kept visible.",
  },
  "spreadsheet": {
    moduleKey: "spreadsheet",
    eyebrow: "Analytics Canvas",
    headline: "Model, explore and publish",
    archetype: "analytics",
    header: "editor",
    density: "spacious",
    navigation: "minimal",
    contentWidth: "full",
    accent: "#7c3aed",
    secondary: "#2563eb",
    signature: "Canvas-first analytical surface that prioritizes models, reports, workbooks and visual exploration.",
  },
  "billing": {
    moduleKey: "billing",
    eyebrow: "Billing Console",
    headline: "Cycles, charges and dunning",
    archetype: "ledger",
    header: "command",
    density: "compact",
    navigation: "rail",
    contentWidth: "wide",
    accent: "#4338ca",
    secondary: "#7c3aed",
    signature: "Dense recurring-billing command center built around cycles, account balances, adjustments and dunning.",
  },
  "payments": {
    moduleKey: "payments",
    eyebrow: "Payments Hub",
    headline: "Collect, allocate and reconcile",
    archetype: "operations",
    header: "command",
    density: "compact",
    navigation: "tabs",
    contentWidth: "wide",
    accent: "#047857",
    secondary: "#10b981",
    signature: "Transaction-focused payments surface with reconciliation, allocation and exception handling up front.",
  },
  "budgeting": {
    moduleKey: "budgeting",
    eyebrow: "Budget Planner",
    headline: "Plan, revise and control spend",
    archetype: "analytics",
    header: "editor",
    density: "balanced",
    navigation: "tabs",
    contentWidth: "wide",
    accent: "#1d4ed8",
    secondary: "#06b6d4",
    signature: "Scenario-oriented budgeting workspace with revision history, approvals and variance visibility.",
  },
  "cash_flow": {
    moduleKey: "cash_flow",
    eyebrow: "Liquidity Monitor",
    headline: "See cash before it becomes urgent",
    archetype: "analytics",
    header: "immersive",
    density: "balanced",
    navigation: "pills",
    contentWidth: "wide",
    accent: "#0369a1",
    secondary: "#14b8a6",
    signature: "Forecast-forward cash workspace emphasizing position, scenarios, liquidity pressure and upcoming movements.",
  },
  "fixed_assets": {
    moduleKey: "fixed_assets",
    eyebrow: "Asset Register",
    headline: "Capitalize, depreciate and dispose",
    archetype: "ledger",
    header: "quiet",
    density: "compact",
    navigation: "rail",
    contentWidth: "wide",
    accent: "#475569",
    secondary: "#2563eb",
    signature: "Register-led fixed asset workspace with depreciation, transfer, disposal and insurance evidence.",
  },
  "tax": {
    moduleKey: "tax",
    eyebrow: "Tax Compliance",
    headline: "Obligations, filings and evidence",
    archetype: "compliance",
    header: "command",
    density: "compact",
    navigation: "tabs",
    contentWidth: "wide",
    accent: "#9f1239",
    secondary: "#dc2626",
    signature: "Deadline and obligation-oriented tax surface designed for filings, payments, rules and compliance evidence.",
  },
  "sales": {
    moduleKey: "sales",
    eyebrow: "Sales Command",
    headline: "Quotes, orders and fulfilment",
    archetype: "pipeline",
    header: "immersive",
    density: "balanced",
    navigation: "tabs",
    contentWidth: "full",
    accent: "#2563eb",
    secondary: "#06b6d4",
    signature: "Commercial command center connecting quotes, approvals, orders, fulfilment and invoicing.",
  },
  "crm": {
    moduleKey: "crm",
    eyebrow: "Revenue Pipeline",
    headline: "Leads, opportunities and forecasts",
    archetype: "pipeline",
    header: "immersive",
    density: "balanced",
    navigation: "rail",
    contentWidth: "full",
    accent: "#7c3aed",
    secondary: "#ec4899",
    signature: "Pipeline-first CRM with stage movement, activity, scoring, forecasts and approvals in one revenue view.",
  },
  "sales_inbox": {
    moduleKey: "sales_inbox",
    eyebrow: "Sales Inbox",
    headline: "Customer conversations that move deals",
    archetype: "inbox",
    header: "split",
    density: "compact",
    navigation: "minimal",
    contentWidth: "full",
    accent: "#2563eb",
    secondary: "#8b5cf6",
    signature: "Conversation-first selling workspace with inbox triage and deal context beside every thread.",
  },
  "cpq": {
    moduleKey: "cpq",
    eyebrow: "CPQ Builder",
    headline: "Configure, price and quote complex offers",
    archetype: "canvas",
    header: "editor",
    density: "spacious",
    navigation: "tabs",
    contentWidth: "full",
    accent: "#4f46e5",
    secondary: "#8b5cf6",
    signature: "Configuration canvas for governed product selection, pricing rules and complex quotation assembly.",
  },
  "commissions": {
    moduleKey: "commissions",
    eyebrow: "Commission Board",
    headline: "Track incentives from earning to payout",
    archetype: "analytics",
    header: "quiet",
    density: "balanced",
    navigation: "tabs",
    contentWidth: "wide",
    accent: "#059669",
    secondary: "#84cc16",
    signature: "Performance and payout workspace that keeps plans, tiers, earnings and payout batches traceable.",
  },
  "appointments": {
    moduleKey: "appointments",
    eyebrow: "Appointment Book",
    headline: "Availability, bookings and reminders",
    archetype: "calendar",
    header: "immersive",
    density: "balanced",
    navigation: "pills",
    contentWidth: "full",
    accent: "#0891b2",
    secondary: "#3b82f6",
    signature: "Schedule-first appointment experience for services, availability, questions, reminders and payment requests.",
  },
  "bookings": {
    moduleKey: "bookings",
    eyebrow: "Booking Calendar",
    headline: "Resources, guests and availability",
    archetype: "calendar",
    header: "editor",
    density: "spacious",
    navigation: "tabs",
    contentWidth: "full",
    accent: "#0284c7",
    secondary: "#14b8a6",
    signature: "Resource calendar designed around availability, guests and booking capacity.",
  },
  "customer_portal": {
    moduleKey: "customer_portal",
    eyebrow: "Customer Portal",
    headline: "Secure self-service for every customer",
    archetype: "service",
    header: "quiet",
    density: "spacious",
    navigation: "minimal",
    contentWidth: "wide",
    accent: "#0f766e",
    secondary: "#2563eb",
    signature: "Customer-facing service surface centered on requests, documents, messages and controlled access.",
  },
  "ecommerce": {
    moduleKey: "ecommerce",
    eyebrow: "Storefront Control",
    headline: "Catalog, orders and online fulfilment",
    archetype: "catalog",
    header: "immersive",
    density: "balanced",
    navigation: "tabs",
    contentWidth: "full",
    accent: "#c2410c",
    secondary: "#f59e0b",
    signature: "Commerce control room combining storefronts, products, order flow and online fulfilment.",
  },
  "checkout": {
    moduleKey: "checkout",
    eyebrow: "Checkout Studio",
    headline: "Payment links and conversion flows",
    archetype: "canvas",
    header: "editor",
    density: "spacious",
    navigation: "pills",
    contentWidth: "wide",
    accent: "#ea580c",
    secondary: "#f43f5e",
    signature: "Conversion-focused checkout builder for sessions, links, events and payment journeys.",
  },
  "loyalty": {
    moduleKey: "loyalty",
    eyebrow: "Loyalty Studio",
    headline: "Points, rewards and retention",
    archetype: "people",
    header: "immersive",
    density: "balanced",
    navigation: "tabs",
    contentWidth: "wide",
    accent: "#db2777",
    secondary: "#7c3aed",
    signature: "Retention workspace built around members, programs, rewards and transaction history.",
  },
  "gift_cards": {
    moduleKey: "gift_cards",
    eyebrow: "Gift Card Center",
    headline: "Issue, redeem and reconcile value",
    archetype: "catalog",
    header: "quiet",
    density: "balanced",
    navigation: "pills",
    contentWidth: "wide",
    accent: "#be185d",
    secondary: "#f97316",
    signature: "Stored-value workspace for programs, card issuance, redemption and balance history.",
  },
  "marketplace": {
    moduleKey: "marketplace",
    eyebrow: "Marketplace Control",
    headline: "Sellers, listings and settlements",
    archetype: "catalog",
    header: "command",
    density: "compact",
    navigation: "rail",
    contentWidth: "full",
    accent: "#7c2d12",
    secondary: "#ea580c",
    signature: "Multi-seller operations console prioritizing listings, orders, seller control and settlement context.",
  },
  "inventory": {
    moduleKey: "inventory",
    eyebrow: "Inventory Control",
    headline: "Stock truth across every location",
    archetype: "operations",
    header: "command",
    density: "compact",
    navigation: "rail",
    contentWidth: "full",
    accent: "#0369a1",
    secondary: "#0f766e",
    signature: "Stock command center emphasizing levels, movements, reservations, reorder risk and transfer work.",
  },
  "warehouse": {
    moduleKey: "warehouse",
    eyebrow: "Warehouse Floor",
    headline: "Pick, move, pack and put away",
    archetype: "operations",
    header: "command",
    density: "compact",
    navigation: "rail",
    contentWidth: "full",
    accent: "#334155",
    secondary: "#0891b2",
    signature: "Execution-heavy warehouse floor with picking batches, operations, packages and location control.",
  },
  "purchase": {
    moduleKey: "purchase",
    eyebrow: "Procurement Desk",
    headline: "Requisition, order, receive and settle",
    archetype: "service",
    header: "quiet",
    density: "compact",
    navigation: "rail",
    contentWidth: "wide",
    accent: "#0f766e",
    secondary: "#65a30d",
    signature: "Procurement workspace organized around demand, supplier orders, receipts, RFQs and price intelligence.",
  },
  "manufacturing": {
    moduleKey: "manufacturing",
    eyebrow: "Manufacturing Floor",
    headline: "Materials, work centers and production",
    archetype: "board",
    header: "command",
    density: "compact",
    navigation: "rail",
    contentWidth: "full",
    accent: "#78350f",
    secondary: "#b45309",
    signature: "Production-floor workspace with manufacturing orders, routing, operations and material reservations.",
  },
  "shipping": {
    moduleKey: "shipping",
    eyebrow: "Shipping Desk",
    headline: "Rates, labels, handoffs and tracking",
    archetype: "operations",
    header: "quiet",
    density: "compact",
    navigation: "tabs",
    contentWidth: "full",
    accent: "#0369a1",
    secondary: "#2563eb",
    signature: "Shipment execution surface for rates, packages, labels, carrier events and delivery exceptions.",
  },
  "demand_planning": {
    moduleKey: "demand_planning",
    eyebrow: "Demand Planner",
    headline: "Forecast demand and replenish intelligently",
    archetype: "analytics",
    header: "editor",
    density: "spacious",
    navigation: "tabs",
    contentWidth: "full",
    accent: "#0f766e",
    secondary: "#06b6d4",
    signature: "Forecasting workspace that connects demand scenarios to replenishment recommendations.",
  },
  "vendor_portal": {
    moduleKey: "vendor_portal",
    eyebrow: "Vendor Portal",
    headline: "Supplier collaboration without inbox chaos",
    archetype: "service",
    header: "quiet",
    density: "balanced",
    navigation: "minimal",
    contentWidth: "wide",
    accent: "#166534",
    secondary: "#0f766e",
    signature: "Supplier-facing collaboration surface for RFQs, documents, messages and purchasing evidence.",
  },
  "barcode": {
    moduleKey: "barcode",
    eyebrow: "Barcode Console",
    headline: "Scan-led receiving, picking and movement",
    archetype: "operations",
    header: "command",
    density: "compact",
    navigation: "minimal",
    contentWidth: "full",
    accent: "#111827",
    secondary: "#2563eb",
    signature: "Scan-first operational console built for speed, device workflows and identifier accuracy.",
  },
  "facilities": {
    moduleKey: "facilities",
    eyebrow: "Facilities Map",
    headline: "Sites, spaces and service requests",
    archetype: "map",
    header: "immersive",
    density: "balanced",
    navigation: "tabs",
    contentWidth: "full",
    accent: "#0f766e",
    secondary: "#14b8a6",
    signature: "Location-oriented facilities workspace for sites, rooms, requests and operating context.",
  },
  "assets": {
    moduleKey: "assets",
    eyebrow: "Asset Operations",
    headline: "Know where every operational asset is",
    archetype: "catalog",
    header: "quiet",
    density: "balanced",
    navigation: "rail",
    contentWidth: "wide",
    accent: "#475569",
    secondary: "#0f766e",
    signature: "Lifecycle workspace for operational assets, assignments, events and supporting documents.",
  },
  "work_orders": {
    moduleKey: "work_orders",
    eyebrow: "Work Order Board",
    headline: "Assign, execute and close operational work",
    archetype: "board",
    header: "command",
    density: "compact",
    navigation: "rail",
    contentWidth: "full",
    accent: "#92400e",
    secondary: "#f59e0b",
    signature: "Dispatch board centered on active jobs, tasks, materials and completion evidence.",
  },
  "inspections": {
    moduleKey: "inspections",
    eyebrow: "Inspection Runner",
    headline: "Check, find and correct",
    archetype: "compliance",
    header: "editor",
    density: "balanced",
    navigation: "tabs",
    contentWidth: "wide",
    accent: "#0f766e",
    secondary: "#84cc16",
    signature: "Checklist-driven inspection surface with findings and corrective actions close to execution.",
  },
  "safety": {
    moduleKey: "safety",
    eyebrow: "Safety Center",
    headline: "Incidents, actions and risk control",
    archetype: "compliance",
    header: "command",
    density: "compact",
    navigation: "rail",
    contentWidth: "wide",
    accent: "#b91c1c",
    secondary: "#f97316",
    signature: "Risk-control workspace that prioritizes incidents, actions, checks and safety accountability.",
  },
  "fleet": {
    moduleKey: "fleet",
    eyebrow: "Fleet Control",
    headline: "Vehicles, assignments and operating cost",
    archetype: "map",
    header: "command",
    density: "compact",
    navigation: "rail",
    contentWidth: "full",
    accent: "#334155",
    secondary: "#2563eb",
    signature: "Vehicle operations surface with assignments, service history and fuel activity.",
  },
  "maintenance": {
    moduleKey: "maintenance",
    eyebrow: "Maintenance Board",
    headline: "Prevent downtime before it starts",
    archetype: "board",
    header: "command",
    density: "compact",
    navigation: "rail",
    contentWidth: "full",
    accent: "#475569",
    secondary: "#eab308",
    signature: "Maintenance queue with equipment context, preventive plans, requests and completed work.",
  },
  "quality": {
    moduleKey: "quality",
    eyebrow: "Quality Control",
    headline: "Inspect, contain and improve",
    archetype: "compliance",
    header: "command",
    density: "compact",
    navigation: "rail",
    contentWidth: "full",
    accent: "#166534",
    secondary: "#84cc16",
    signature: "Quality workspace for checks, alerts, issues, corrective actions and control points.",
  },
  "field_services": {
    moduleKey: "field_services",
    eyebrow: "Field Service Dispatch",
    headline: "Schedule crews and complete work on site",
    archetype: "map",
    header: "command",
    density: "compact",
    navigation: "rail",
    contentWidth: "full",
    accent: "#0369a1",
    secondary: "#14b8a6",
    signature: "Dispatch-oriented field service surface for orders, visits, materials and checklists.",
  },
  "planning": {
    moduleKey: "planning",
    eyebrow: "Planning Board",
    headline: "Capacity, assignments and schedule",
    archetype: "calendar",
    header: "editor",
    density: "spacious",
    navigation: "tabs",
    contentWidth: "full",
    accent: "#4f46e5",
    secondary: "#06b6d4",
    signature: "Resource planning workspace balancing shifts, assignments and available capacity.",
  },
  "plm": {
    moduleKey: "plm",
    eyebrow: "Product Lifecycle",
    headline: "Versions, engineering changes and approvals",
    archetype: "document",
    header: "editor",
    density: "balanced",
    navigation: "tabs",
    contentWidth: "wide",
    accent: "#475569",
    secondary: "#7c3aed",
    signature: "Engineering change workspace centered on product versions, controlled change and approval evidence.",
  },
  "employees": {
    moduleKey: "employees",
    eyebrow: "People Directory",
    headline: "Employees, contracts and lifecycle",
    archetype: "people",
    header: "quiet",
    density: "spacious",
    navigation: "rail",
    contentWidth: "full",
    accent: "#7c3aed",
    secondary: "#2563eb",
    signature: "Employee-centered directory with contracts, lifecycle events, certifications and assignments.",
  },
  "payroll": {
    moduleKey: "payroll",
    eyebrow: "Payroll Control",
    headline: "Periods, computation and payslips",
    archetype: "ledger",
    header: "command",
    density: "compact",
    navigation: "rail",
    contentWidth: "full",
    accent: "#166534",
    secondary: "#2563eb",
    signature: "Payroll command surface with periods, runs, rules, work entries, payslips and payment batches.",
  },
  "attendance": {
    moduleKey: "attendance",
    eyebrow: "Attendance Monitor",
    headline: "Clock events, exceptions and corrections",
    archetype: "analytics",
    header: "command",
    density: "compact",
    navigation: "tabs",
    contentWidth: "full",
    accent: "#0369a1",
    secondary: "#7c3aed",
    signature: "Real-time attendance surface for clocking, exceptions, corrections, overtime and device inputs.",
  },
  "shifts": {
    moduleKey: "shifts",
    eyebrow: "Shift Planner",
    headline: "Roster people and protect coverage",
    archetype: "calendar",
    header: "editor",
    density: "spacious",
    navigation: "tabs",
    contentWidth: "full",
    accent: "#4f46e5",
    secondary: "#ec4899",
    signature: "Roster-first staffing planner with templates, open shifts, swaps and availability.",
  },
  "onboarding": {
    moduleKey: "onboarding",
    eyebrow: "Onboarding Journey",
    headline: "Guide every new hire to day-one readiness",
    archetype: "people",
    header: "immersive",
    density: "balanced",
    navigation: "pills",
    contentWidth: "wide",
    accent: "#7c3aed",
    secondary: "#14b8a6",
    signature: "Journey-style onboarding workspace for templates, tasks, documents, equipment and check-ins.",
  },
  "learning": {
    moduleKey: "learning",
    eyebrow: "Learning Hub",
    headline: "Courses, paths and workforce capability",
    archetype: "catalog",
    header: "immersive",
    density: "spacious",
    navigation: "tabs",
    contentWidth: "full",
    accent: "#2563eb",
    secondary: "#8b5cf6",
    signature: "Learning catalog and progress workspace with paths, assessments, attempts and certifications.",
  },
  "benefits": {
    moduleKey: "benefits",
    eyebrow: "Benefits Center",
    headline: "Eligibility, enrollment and claims",
    archetype: "people",
    header: "quiet",
    density: "balanced",
    navigation: "tabs",
    contentWidth: "wide",
    accent: "#db2777",
    secondary: "#7c3aed",
    signature: "Employee benefits workspace organized around plans, eligibility, enrollment and claims.",
  },
  "org_chart": {
    moduleKey: "org_chart",
    eyebrow: "Organization Map",
    headline: "See structure, roles and succession",
    archetype: "map",
    header: "immersive",
    density: "spacious",
    navigation: "minimal",
    contentWidth: "full",
    accent: "#6366f1",
    secondary: "#8b5cf6",
    signature: "Visual organization surface for positions, reporting structure, history and succession planning.",
  },
  "appraisals": {
    moduleKey: "appraisals",
    eyebrow: "Performance Review",
    headline: "Goals, feedback and calibration",
    archetype: "people",
    header: "editor",
    density: "balanced",
    navigation: "tabs",
    contentWidth: "wide",
    accent: "#7c3aed",
    secondary: "#ec4899",
    signature: "Review-cycle workspace for goals, competencies, feedback and calibration.",
  },
  "recruitment": {
    moduleKey: "recruitment",
    eyebrow: "Hiring Pipeline",
    headline: "Requisitions, candidates and offers",
    archetype: "pipeline",
    header: "immersive",
    density: "balanced",
    navigation: "rail",
    contentWidth: "full",
    accent: "#2563eb",
    secondary: "#8b5cf6",
    signature: "Candidate pipeline with requisitions, applicants, interviews, scorecards and offers.",
  },
  "time_off": {
    moduleKey: "time_off",
    eyebrow: "Leave Planner",
    headline: "Requests, balances and availability",
    archetype: "calendar",
    header: "quiet",
    density: "balanced",
    navigation: "tabs",
    contentWidth: "wide",
    accent: "#0891b2",
    secondary: "#22c55e",
    signature: "Calendar-led leave workspace for balances, accruals, requests and blackout periods.",
  },
  "timesheets": {
    moduleKey: "timesheets",
    eyebrow: "Timesheet Desk",
    headline: "Capture time, submit and approve",
    archetype: "ledger",
    header: "quiet",
    density: "compact",
    navigation: "tabs",
    contentWidth: "wide",
    accent: "#0f766e",
    secondary: "#2563eb",
    signature: "Period-based time entry workspace with submission and approval visibility.",
  },
  "marketing_automation": {
    moduleKey: "marketing_automation",
    eyebrow: "Journey Builder",
    headline: "Automate audiences and campaign journeys",
    archetype: "canvas",
    header: "editor",
    density: "spacious",
    navigation: "rail",
    contentWidth: "full",
    accent: "#7c3aed",
    secondary: "#ec4899",
    signature: "Automation canvas for workflows, steps, segments and run outcomes.",
  },
  "email_marketing": {
    moduleKey: "email_marketing",
    eyebrow: "Email Studio",
    headline: "Design, send and measure campaigns",
    archetype: "canvas",
    header: "immersive",
    density: "spacious",
    navigation: "tabs",
    contentWidth: "full",
    accent: "#2563eb",
    secondary: "#7c3aed",
    signature: "Campaign studio centered on email content, audiences, templates, delivery and engagement.",
  },
  "sms_marketing": {
    moduleKey: "sms_marketing",
    eyebrow: "SMS Campaigns",
    headline: "Reach customers with concise mobile campaigns",
    archetype: "inbox",
    header: "command",
    density: "compact",
    navigation: "tabs",
    contentWidth: "wide",
    accent: "#0f766e",
    secondary: "#22c55e",
    signature: "Message-delivery workspace for campaigns, templates, segments, recipients and opt-outs.",
  },
  "social_marketing": {
    moduleKey: "social_marketing",
    eyebrow: "Social Studio",
    headline: "Publish, listen and measure",
    archetype: "canvas",
    header: "immersive",
    density: "spacious",
    navigation: "tabs",
    contentWidth: "full",
    accent: "#db2777",
    secondary: "#7c3aed",
    signature: "Social content studio combining accounts, publishing, campaigns, inbox activity and metrics.",
  },
  "ads": {
    moduleKey: "ads",
    eyebrow: "Ads Manager",
    headline: "Spend deliberately and optimize performance",
    archetype: "analytics",
    header: "command",
    density: "compact",
    navigation: "rail",
    contentWidth: "full",
    accent: "#2563eb",
    secondary: "#8b5cf6",
    signature: "Paid-media control surface for accounts, campaigns, spend and daily performance.",
  },
  "seo": {
    moduleKey: "seo",
    eyebrow: "SEO Monitor",
    headline: "Visibility, keywords and technical issues",
    archetype: "analytics",
    header: "quiet",
    density: "balanced",
    navigation: "tabs",
    contentWidth: "full",
    accent: "#059669",
    secondary: "#0ea5e9",
    signature: "Search-performance workspace for sites, keywords, rankings and issue remediation.",
  },
  "landing_pages": {
    moduleKey: "landing_pages",
    eyebrow: "Landing Page Studio",
    headline: "Build pages that convert",
    archetype: "canvas",
    header: "editor",
    density: "spacious",
    navigation: "minimal",
    contentWidth: "full",
    accent: "#ea580c",
    secondary: "#ec4899",
    signature: "Page-building workspace combining landing pages, forms and submission outcomes.",
  },
  "lead_capture": {
    moduleKey: "lead_capture",
    eyebrow: "Lead Capture",
    headline: "Turn inbound interest into routed opportunities",
    archetype: "pipeline",
    header: "command",
    density: "compact",
    navigation: "tabs",
    contentWidth: "wide",
    accent: "#2563eb",
    secondary: "#14b8a6",
    signature: "Inbound lead workspace for forms, entries, events and CRM routing.",
  },
  "web_analytics": {
    moduleKey: "web_analytics",
    eyebrow: "Web Analytics",
    headline: "Understand acquisition, behavior and conversion",
    archetype: "analytics",
    header: "immersive",
    density: "spacious",
    navigation: "tabs",
    contentWidth: "full",
    accent: "#0369a1",
    secondary: "#7c3aed",
    signature: "Digital analytics surface for sessions, events, conversions and site performance.",
  },
  "projects": {
    moduleKey: "projects",
    eyebrow: "Project Delivery",
    headline: "Tasks, milestones, capacity and budget",
    archetype: "board",
    header: "immersive",
    density: "balanced",
    navigation: "rail",
    contentWidth: "full",
    accent: "#2563eb",
    secondary: "#8b5cf6",
    signature: "Delivery workspace combining project boards, milestones, dependencies, resources and budget.",
  },
  "helpdesk": {
    moduleKey: "helpdesk",
    eyebrow: "Support Desk",
    headline: "Tickets, SLA risk and knowledge",
    archetype: "service",
    header: "command",
    density: "compact",
    navigation: "rail",
    contentWidth: "full",
    accent: "#0369a1",
    secondary: "#8b5cf6",
    signature: "Queue-first support desk with SLA tracking, messages, escalation and knowledge context.",
  },
  "events": {
    moduleKey: "events",
    eyebrow: "Event Command",
    headline: "Sessions, registrations and tickets",
    archetype: "calendar",
    header: "immersive",
    density: "balanced",
    navigation: "tabs",
    contentWidth: "full",
    accent: "#7c3aed",
    secondary: "#ec4899",
    signature: "Event operations workspace for programs, sessions, registrations and ticket activity.",
  },
  "referrals": {
    moduleKey: "referrals",
    eyebrow: "Referral Growth",
    headline: "Programs, conversions and rewards",
    archetype: "pipeline",
    header: "quiet",
    density: "balanced",
    navigation: "tabs",
    contentWidth: "wide",
    accent: "#059669",
    secondary: "#84cc16",
    signature: "Growth workspace tracking referral programs from introduction through conversion and reward.",
  },
  "rentals": {
    moduleKey: "rentals",
    eyebrow: "Rental Desk",
    headline: "Reserve, contract and charge",
    archetype: "calendar",
    header: "quiet",
    density: "balanced",
    navigation: "rail",
    contentWidth: "wide",
    accent: "#0f766e",
    secondary: "#f59e0b",
    signature: "Availability and contract workspace for rental items, reservations and charges.",
  },
  "subscriptions": {
    moduleKey: "subscriptions",
    eyebrow: "Subscription Desk",
    headline: "Plans, renewals and usage billing",
    archetype: "ledger",
    header: "command",
    density: "compact",
    navigation: "rail",
    contentWidth: "full",
    accent: "#4f46e5",
    secondary: "#06b6d4",
    signature: "Recurring revenue workspace for plans, subscriptions, changes, renewals and usage charges.",
  },
  "pos_shop": {
    moduleKey: "pos_shop",
    eyebrow: "Retail POS",
    headline: "Sell quickly and reconcile every shift",
    archetype: "pos",
    header: "command",
    density: "compact",
    navigation: "minimal",
    contentWidth: "full",
    accent: "#111827",
    secondary: "#f97316",
    signature: "Counter-first retail console optimized for sessions, payments, cash movement and returns.",
  },
  "pos_restaurant": {
    moduleKey: "pos_restaurant",
    eyebrow: "Restaurant POS",
    headline: "Tables, orders and kitchen flow",
    archetype: "pos",
    header: "command",
    density: "compact",
    navigation: "minimal",
    contentWidth: "full",
    accent: "#7c2d12",
    secondary: "#ef4444",
    signature: "Hospitality console organized around floors, tables, orders, preparation and settlement.",
  },
  "surveys": {
    moduleKey: "surveys",
    eyebrow: "Survey Studio",
    headline: "Ask, collect and understand responses",
    archetype: "canvas",
    header: "editor",
    density: "spacious",
    navigation: "tabs",
    contentWidth: "wide",
    accent: "#7c3aed",
    secondary: "#06b6d4",
    signature: "Research workspace for survey design, questions, responses and answer analysis.",
  },
  "documents": {
    moduleKey: "documents",
    eyebrow: "Document Library",
    headline: "Store, version, approve and share",
    archetype: "library",
    header: "quiet",
    density: "spacious",
    navigation: "rail",
    contentWidth: "full",
    accent: "#475569",
    secondary: "#2563eb",
    signature: "Library-oriented document workspace with folders, versions, approvals, sharing and access history.",
  },
  "sign": {
    moduleKey: "sign",
    eyebrow: "Signature Room",
    headline: "Prepare, send and prove completion",
    archetype: "document",
    header: "editor",
    density: "balanced",
    navigation: "tabs",
    contentWidth: "wide",
    accent: "#4f46e5",
    secondary: "#0f766e",
    signature: "Document-signing workspace for templates, signers, fields, authentication and completion certificates.",
  },
  "mail": {
    moduleKey: "mail",
    eyebrow: "Mail",
    headline: "Business email with SaMi context",
    archetype: "inbox",
    header: "split",
    density: "compact",
    navigation: "minimal",
    contentWidth: "full",
    accent: "#2563eb",
    secondary: "#06b6d4",
    signature: "Mail-first surface designed around threads, accounts and business context.",
  },
  "chat": {
    moduleKey: "chat",
    eyebrow: "Team Chat",
    headline: "Fast conversations inside the workspace",
    archetype: "inbox",
    header: "split",
    density: "compact",
    navigation: "minimal",
    contentWidth: "full",
    accent: "#7c3aed",
    secondary: "#ec4899",
    signature: "Conversation workspace with channels, membership, messages and reactions.",
  },
  "meetings": {
    moduleKey: "meetings",
    eyebrow: "Meeting Room",
    headline: "Schedule, meet and capture outcomes",
    archetype: "calendar",
    header: "immersive",
    density: "balanced",
    navigation: "tabs",
    contentWidth: "full",
    accent: "#2563eb",
    secondary: "#7c3aed",
    signature: "Meeting workspace for participants, notes and scheduled collaboration.",
  },
  "calendar": {
    moduleKey: "calendar",
    eyebrow: "Calendar",
    headline: "See work across time",
    archetype: "calendar",
    header: "editor",
    density: "spacious",
    navigation: "minimal",
    contentWidth: "full",
    accent: "#2563eb",
    secondary: "#14b8a6",
    signature: "Calendar-first workspace for shared calendars, events and attendees.",
  },
  "team_inbox": {
    moduleKey: "team_inbox",
    eyebrow: "Team Inbox",
    headline: "Assign shared conversations and own the response",
    archetype: "inbox",
    header: "split",
    density: "compact",
    navigation: "rail",
    contentWidth: "full",
    accent: "#0f766e",
    secondary: "#2563eb",
    signature: "Shared-inbox surface built around assignment, ownership and collaborative replies.",
  },
  "whiteboard": {
    moduleKey: "whiteboard",
    eyebrow: "Whiteboard",
    headline: "Think visually with your team",
    archetype: "canvas",
    header: "editor",
    density: "spacious",
    navigation: "minimal",
    contentWidth: "full",
    accent: "#7c3aed",
    secondary: "#ec4899",
    signature: "Visual collaboration canvas for boards, members and versioned ideas.",
  }
};

export function getSamiAppUiProfile(
  moduleKeyInput: string,
): SamiAppUiProfile {
  const moduleKey =
    moduleKeyInput
      .trim()
      .toLowerCase();

  return SAMI_APP_UI_PROFILES[
    moduleKey
  ] || {
    moduleKey,
    eyebrow:
      'SaMi application',
    headline:
      'Operate with clarity',
    archetype:
      'service',
    header:
      'quiet',
    density:
      'balanced',
    navigation:
      'tabs',
    contentWidth:
      'wide',
    accent:
      '#2563eb',
    secondary:
      '#7c3aed',
    signature:
      'A dedicated SaMi application surface with company-scoped controls, records and insights.',
  };
}

export const SAMI_APP_UI_PROFILE_COUNT =
  Object.keys(
    SAMI_APP_UI_PROFILES,
  ).length;
