import 'server-only';
import type { PoolClient } from 'pg';
import { requireEnterpriseModuleTableContext } from '@/lib/apps/enterprise/service';
import { recordWorkspaceAuditEvent } from '@/lib/services/workspace-activity';
import { AccountingInputError, accountingDate, accountingId } from './validation';
import { calculateAccountingTaxes, type AccountingTaxRule } from './tax-engine';

type Context=Awaited<ReturnType<typeof requireEnterpriseModuleTableContext>>;
const bodyOf=(input:unknown)=>{if(!input||typeof input!=='object'||Array.isArray(input))throw new AccountingInputError('Enter valid tax details.');return input as Record<string,unknown>;};
function text(v:unknown,max:number,label:string,required=false){if(v!=null&&typeof v!=='string')throw new AccountingInputError(label+' must contain text.');const s=typeof v==='string'?v.trim():'';if(required&&!s)throw new AccountingInputError(label+' is required.');if(s.length>max)throw new AccountingInputError(label+' must be at most '+max+' characters.');return s;}
function choice<T extends string>(v:unknown,values:readonly T[],label:string):T{if(typeof v!=='string'||!values.includes(v as T))throw new AccountingInputError('Choose a valid '+label+'.');return v as T;}
function decimal(v:unknown,label:string,max:number){const s=String(v??'').trim();if(!/^\d{1,3}(?:\.\d{1,4})?$/.test(s))throw new AccountingInputError(label+' is invalid.');const n=Number(s);if(n<0||n>max)throw new AccountingInputError(label+' must be between 0 and '+max+'.');return n.toFixed(4);}
function money(v:unknown,label:string){const s=String(v??'0').trim();if(!/^\d{1,16}(?:\.\d{1,2})?$/.test(s))throw new AccountingInputError(label+' is invalid.');return Number(s).toFixed(2);}
const optionalId=(v:unknown)=>v?accountingId(v):null;
async function audit(context:Context,id:string,action:string,metadata:Record<string,unknown>={}){await recordWorkspaceAuditEvent({tenantId:context.tenantId,companyId:context.companyId,userId:context.userId,action:'accounting.tax.'+action,module:'accounting',resourceType:'accounting_tax_codes',resourceId:id,summary:'Accounting tax '+action,result:'success',metadata}).catch(e=>console.error('[Accounting] Tax audit failed',e));}
function rule(row:Record<string,unknown>):AccountingTaxRule{return{id:String(row.id),code:String(row.code),name:String(row.name),scope:String(row.scope) as AccountingTaxRule['scope'],behavior:String(row.behavior) as AccountingTaxRule['behavior'],computation:String(row.computation) as AccountingTaxRule['computation'],rate:String(row.rate),fixedAmount:String(row.fixed_amount),priceIncluded:Boolean(row.price_included),includeBaseAmount:Boolean(row.include_base_amount),recoverablePercent:String(row.recoverable_percent),sequence:Number(row.sequence||100)};}

export async function getAccountingTaxes(){
 const context=await requireEnterpriseModuleTableContext('accounting','accounting_tax_codes','view');
 const [codes,groups,accounts,register]=await Promise.all([
  context.pool.query(`SELECT t.id::text,t.code,t.name,t.scope,t.behavior,t.computation,t.rate::text,t.fixed_amount::text,t.price_included,t.include_base_amount,t.recoverable_percent::text,t.tax_account_id::text,t.recoverable_account_id::text,t.jurisdiction_code,t.reporting_code,t.effective_from::text,t.effective_to::text,t.sequence,t.status FROM accounting_tax_codes t WHERE t.company_id=$1 AND t.deleted_at IS NULL ORDER BY t.status,t.sequence,t.code`,[context.companyId]),
  context.pool.query(`SELECT g.id::text,g.code,g.name,g.scope,g.status,COALESCE(json_agg(json_build_object('id',t.id::text,'code',t.code,'name',t.name,'sequence',l.sequence) ORDER BY l.sequence,t.code) FILTER(WHERE t.id IS NOT NULL),'[]'::json) AS taxes FROM accounting_tax_groups g LEFT JOIN accounting_tax_group_lines l ON l.company_id=g.company_id AND l.group_id=g.id AND l.deleted_at IS NULL LEFT JOIN accounting_tax_codes t ON t.company_id=l.company_id AND t.id=l.tax_code_id AND t.deleted_at IS NULL WHERE g.company_id=$1 AND g.deleted_at IS NULL GROUP BY g.id ORDER BY g.status,g.code`,[context.companyId]),
  context.pool.query(`SELECT id::text,code,name,account_type FROM accounts WHERE company_id=$1 AND deleted_at IS NULL AND is_active=TRUE ORDER BY code`,[context.companyId]),
  context.pool.query(`SELECT e.id::text,e.transaction_date::text,e.source_module,e.source_type,e.source_id,e.taxable_amount::text,e.tax_amount::text,e.recoverable_amount::text,e.nonrecoverable_amount::text,e.currency,e.direction,t.code,t.name FROM accounting_tax_ledger_entries e JOIN accounting_tax_codes t ON t.company_id=e.company_id AND t.id=e.tax_code_id WHERE e.company_id=$1 AND e.deleted_at IS NULL ORDER BY e.transaction_date DESC,e.created_at DESC LIMIT 100`,[context.companyId]),
 ]);
 return{companyId:context.companyId,currency:context.company.currentCompany.currency,codes:codes.rows,groups:groups.rows,accounts:accounts.rows,register:register.rows,metrics:{activeCodes:codes.rows.filter(r=>r.status==='active').length,groups:groups.rows.filter(r=>r.status==='active').length,registerEntries:register.rows.length}};
}
export type AccountingTaxesWorkspace=Awaited<ReturnType<typeof getAccountingTaxes>>;

export async function createAccountingTaxCode(input:unknown){
 const context=await requireEnterpriseModuleTableContext('accounting','accounting_tax_codes','create'),b=bodyOf(input);
 if(accountingId(b.expectedCompanyId)!==context.companyId)throw new AccountingInputError('Your active company changed. Reload Accounting before saving.');
 const code=text(b.code,60,'Tax code',true).toUpperCase(),name=text(b.name,180,'Tax name',true),scope=choice(b.scope,['sale','purchase','both','withholding'] as const,'tax scope'),behavior=choice(b.behavior,['add','withhold'] as const,'tax behavior'),computation=choice(b.computation,['percent','fixed'] as const,'calculation method');
 const rate=computation==='percent'?decimal(b.rate,'Tax rate',100):'0.0000',fixedAmount=computation==='fixed'?money(b.fixedAmount,'Fixed tax amount'):'0.00',priceIncluded=Boolean(b.priceIncluded),includeBaseAmount=Boolean(b.includeBaseAmount),recoverablePercent=decimal(b.recoverablePercent??((scope==='purchase'||scope==='both')?100:0),'Recoverable percent',100),taxAccountId=optionalId(b.taxAccountId),recoverableAccountId=optionalId(b.recoverableAccountId),effectiveFrom=b.effectiveFrom?accountingDate(b.effectiveFrom):null,effectiveTo=b.effectiveTo?accountingDate(b.effectiveTo):null;
 if(effectiveFrom&&effectiveTo&&effectiveTo<effectiveFrom)throw new AccountingInputError('Tax effective end date cannot be before its start date.');
 if(behavior==='withhold'&&priceIncluded)throw new AccountingInputError('Withholding taxes cannot be price included.');
 if(priceIncluded&&computation!=='percent')throw new AccountingInputError('Only percentage taxes can be price included.');
 if(priceIncluded&&includeBaseAmount)throw new AccountingInputError('Price-included taxes cannot increase the base of later taxes.');
 if((scope==='purchase'||scope==='both')&&Number(recoverablePercent)>0&&!recoverableAccountId)throw new AccountingInputError('Map a recoverable/input tax account for recoverable purchase tax.');
 if(behavior==='add'&&!taxAccountId&&!recoverableAccountId)throw new AccountingInputError('Map at least one tax control account.');
 const client=await context.pool.connect();try{await client.query('BEGIN');const ids=[taxAccountId,recoverableAccountId].filter(Boolean);if(ids.length){const valid=await client.query(`SELECT id FROM accounts WHERE company_id=$1 AND id=ANY($2::uuid[]) AND deleted_at IS NULL AND is_active=TRUE`,[context.companyId,ids]);if(valid.rows.length!==new Set(ids).size)throw new AccountingInputError('Every tax ledger mapping must use an active company account.');}
 const result=await client.query(`INSERT INTO accounting_tax_codes(company_id,code,name,scope,behavior,computation,rate,fixed_amount,price_included,include_base_amount,recoverable_percent,tax_account_id,recoverable_account_id,jurisdiction_code,reporting_code,effective_from,effective_to,sequence,status,created_by,updated_by) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12,$13,$14,$15,$16,$17,$18,'active',$19,$19) RETURNING id::text`,[context.companyId,code,name,scope,behavior,computation,rate,fixedAmount,priceIncluded,includeBaseAmount,recoverablePercent,taxAccountId,recoverableAccountId,text(b.jurisdictionCode,80,'Jurisdiction code')||null,text(b.reportingCode,80,'Reporting code')||null,effectiveFrom,effectiveTo,Math.max(0,Math.min(100000,Number(b.sequence??100)||100)),context.userId]);
 await client.query('COMMIT');const id=String(result.rows[0].id);await audit(context,id,'created',{code,scope});return{id};}catch(e){try{await client.query('ROLLBACK');}catch{}if((e as {code?:string})?.code==='23505')throw new AccountingInputError('This tax code already exists in the company.');throw e;}finally{client.release();}
}
export async function setAccountingTaxCodeStatus(input:unknown){const context=await requireEnterpriseModuleTableContext('accounting','accounting_tax_codes','edit'),b=bodyOf(input),id=accountingId(b.taxCodeId),status=choice(b.status,['active','archived'] as const,'tax status');const r=await context.pool.query(`UPDATE accounting_tax_codes SET status=$3,updated_by=$4,updated_at=NOW() WHERE company_id=$1 AND id=$2 AND deleted_at IS NULL RETURNING id::text,code`,[context.companyId,id,status,context.userId]);if(!r.rows[0])throw new AccountingInputError('Tax code not found.');await audit(context,id,status,{code:r.rows[0].code});return{id,status};}
export async function createAccountingTaxGroup(input:unknown){const context=await requireEnterpriseModuleTableContext('accounting','accounting_tax_groups','create'),b=bodyOf(input);if(accountingId(b.expectedCompanyId)!==context.companyId)throw new AccountingInputError('Your active company changed. Reload Accounting before saving.');const code=text(b.code,60,'Group code',true).toUpperCase(),name=text(b.name,180,'Group name',true),scope=choice(b.scope,['sale','purchase','both','withholding'] as const,'group scope');if(!Array.isArray(b.taxCodeIds)||b.taxCodeIds.length<1||b.taxCodeIds.length>30)throw new AccountingInputError('Choose between 1 and 30 tax codes.');const ids=b.taxCodeIds.map(accountingId);if(new Set(ids).size!==ids.length)throw new AccountingInputError('A tax code can appear only once in a group.');const client=await context.pool.connect();try{await client.query('BEGIN');const v=await client.query(`SELECT id::text,status FROM accounting_tax_codes WHERE company_id=$1 AND id=ANY($2::uuid[]) AND deleted_at IS NULL FOR SHARE`,[context.companyId,ids]);if(v.rows.length!==ids.length||v.rows.some(r=>r.status!=='active'))throw new AccountingInputError('Every group member must be an active company tax code.');const c=await client.query(`INSERT INTO accounting_tax_groups(company_id,code,name,scope,status,created_by,updated_by) VALUES($1,$2,$3,$4,'active',$5,$5) RETURNING id::text`,[context.companyId,code,name,scope,context.userId]);const id=String(c.rows[0].id);for(let i=0;i<ids.length;i++)await client.query(`INSERT INTO accounting_tax_group_lines(company_id,group_id,tax_code_id,sequence,created_by) VALUES($1,$2,$3,$4,$5)`,[context.companyId,id,ids[i],(i+1)*10,context.userId]);await client.query('COMMIT');await audit(context,id,'group_created',{code,count:ids.length});return{id};}catch(e){try{await client.query('ROLLBACK');}catch{}throw e;}finally{client.release();}}
export async function previewAccountingTaxes(input:unknown){const context=await requireEnterpriseModuleTableContext('accounting','accounting_tax_codes','view'),b=bodyOf(input),amount=money(b.amount,'Taxable amount'),date=accountingDate(b.date);if(!Array.isArray(b.taxCodeIds)||b.taxCodeIds.length<1)throw new AccountingInputError('Choose at least one tax code.');const ids=b.taxCodeIds.map(accountingId);const r=await context.pool.query(`SELECT * FROM accounting_tax_codes WHERE company_id=$1 AND id=ANY($2::uuid[]) AND deleted_at IS NULL AND status='active' AND (effective_from IS NULL OR effective_from<=$3) AND (effective_to IS NULL OR effective_to>=$3) ORDER BY sequence,code`,[context.companyId,ids,date]);if(r.rows.length!==new Set(ids).size)throw new AccountingInputError('One or more selected taxes are inactive or not effective on this date.');return calculateAccountingTaxes(amount,r.rows.map(rule));}
export async function recordAccountingTaxLedgerEntries(client:PoolClient,input:{companyId:string;userId:string;sourceModule:string;sourceType:string;sourceId:string;sourceEventKey:string;transactionDate:string;currency:string;journalId?:string|null;direction:'sale'|'purchase'|'withholding';components:ReturnType<typeof calculateAccountingTaxes>['components'];}){for(const c of input.components)await client.query(`INSERT INTO accounting_tax_ledger_entries(company_id,tax_code_id,journal_id,source_module,source_type,source_id,source_event_key,transaction_date,taxable_amount,tax_amount,recoverable_amount,nonrecoverable_amount,currency,direction,created_by) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12,$13,$14,$15) ON CONFLICT (company_id,source_module,source_event_key,tax_code_id) WHERE deleted_at IS NULL DO NOTHING`,[input.companyId,c.taxCodeId,input.journalId||null,input.sourceModule,input.sourceType,input.sourceId,input.sourceEventKey,input.transactionDate,c.taxableAmount,c.taxAmount,c.recoverableAmount,c.nonrecoverableAmount,input.currency.toUpperCase(),input.direction,input.userId]);}
