import { NextRequest, NextResponse } from 'next/server';
import { createAccountingTaxCode,createAccountingTaxGroup,getAccountingTaxes,previewAccountingTaxes,setAccountingTaxCodeStatus } from '@/lib/apps/accounting/taxes';
import { AccountingInputError } from '@/lib/apps/accounting/validation';
import { EnterpriseModuleError } from '@/lib/apps/enterprise/service';
import { TenantContextError } from '@/lib/auth/tenant-context';
export const runtime='nodejs';export const dynamic='force-dynamic';
const respond=(body:object,status=200)=>NextResponse.json(body,{status,headers:{'Cache-Control':'no-store'}});
function failure(error:unknown){if(error instanceof AccountingInputError||error instanceof SyntaxError)return respond({error:error instanceof SyntaxError?'Enter valid tax data.':error.message},400);if(error instanceof TenantContextError)return respond({error:error.message},error.code==='UNAUTHENTICATED'?401:403);if(error instanceof EnterpriseModuleError)return respond({error:error.message},error.code==='MODULE_PERMISSION_REQUIRED'?403:409);console.error('[Accounting] Tax action failed',error);return respond({error:'The tax action could not be completed. Retry or contact your administrator.'},500);}
export async function GET(){try{return respond({success:true,result:await getAccountingTaxes()});}catch(error){return failure(error);}}
export async function POST(request:NextRequest){const origin=request.headers.get('origin');if(request.headers.get('sec-fetch-site')==='cross-site'||(origin&&origin!==request.nextUrl.origin))return respond({error:'This request could not be verified.'},403);try{const raw=await request.text();if(new TextEncoder().encode(raw).length>96*1024)return respond({error:'Tax request is too large.'},413);const body=JSON.parse(raw) as Record<string,unknown>;const result=body.action==='create-code'?await createAccountingTaxCode(body):body.action==='set-status'?await setAccountingTaxCodeStatus(body):body.action==='create-group'?await createAccountingTaxGroup(body):body.action==='preview'?await previewAccountingTaxes(body):(()=>{throw new AccountingInputError('Choose a supported tax action.');})();return respond({success:true,result});}catch(error){return failure(error);}}
