import {
  defineSamiModule,
  type SamiModuleManifest,
} from '@/lib/modules/types';

import {
  ADDITIONAL_FIRST_PARTY_SAMI_MODULES,
} from '@/lib/modules/additional-first-party';

import {
  withEnterpriseModuleDefaults,
} from '@/lib/modules/enterprise-contract';

/*
 * Canonical first-party module manifests.
 *
 * This is SaMi's equivalent of Odoo's module manifest layer. The
 * compatibility app catalog, navigation, lifecycle, search, dashboard,
 * automation and AI runtimes must project from or validate against these
 * manifests rather than inventing private app metadata.
 *
 * Individual modules can progressively enrich their manifest with models /
 * resources, views, actions, permissions, policies and extension hooks as
 * their business implementation is built.
 */
const BASE_FIRST_PARTY_SAMI_MODULES:
  SamiModuleManifest[] = [
  defineSamiModule({
    key: "accounting",
    name: "Accounting",
    version: '1.0.0',
    description: "Manage accounts, journals, balances and financial reporting.",
    category: "finance",
    icon: "calculator",
    route: "apps/accounting",
    application: true,
    installable: true,
    autoInstall: false,
    recommended: true,
    depends: [],
    optionalDepends: [],
    schemaPath: "lib/apps/accounting/schema.sql",
    migrationNamespace: "accounting",
    navigation: [
      {
        key: "accounting.root",
        label: "Accounting",
        href: "/apps/accounting",
        iconKey: "calculator",
        parentKey: null,
        actionKey: "accounting.open",
        order: 10,
      },
    ],
    actions: [
      {
        key: "accounting.open",
        name: "Open Accounting",
        type: 'route',
        href: "/apps/accounting",
        viewKeys: ["accounting.workspace"],
        target: 'current',
      },
    ],
    views: [
      {
        key: "accounting.workspace",
        name: "Accounting workspace",
        type: 'workspace',
        route: "/apps/accounting",
        priority: 10,
      },
    ],
    resources: [],
    security: {
      permissions: [],
      recordPolicies: [],
      fieldPolicies: [],
    },
    settings: [],
    extensions: {
      dashboard: false,
      search: false,
      notifications: false,
      activity: false,
      automationTriggers: false,
      automationActions: false,
      aiTools: false,
      integrationProviders: false,
      apiEndpoints: false,
      dataExport: false,
      dataErasure: false,
    },
  }),

  defineSamiModule({
    key: "invoicing",
    name: "Invoicing",
    version: '2.2.0',
    description: "Create invoices, collect payments, manage receivables, credit notes and recurring billing.",
    category: "finance",
    icon: "receipt",
    route: "apps/invoicing",
    application: true,
    installable: true,
    autoInstall: false,
    recommended: true,
    depends: [],
    optionalDepends: [
      'accounting',
      'payments',
      'crm',
      'sales',
      'inventory',
      'tax',
      'subscriptions',
      'customer_portal',
      'documents',
      'sign',
      'cash_flow',
    ],
    schemaPath: "lib/apps/invoicing/schema.sql",
    migrationNamespace: "invoicing",
    navigation: [
      {
        key: "invoicing.root",
        label: "Invoicing",
        href: "/apps/invoicing",
        iconKey: "receipt",
        parentKey: null,
        actionKey: "invoicing.open",
        order: 10,
      },
      {
        key: "invoicing.invoices",
        label: "Invoices",
        href: "/apps/invoicing",
        iconKey: "receipt",
        parentKey: "invoicing.root",
        actionKey: "invoicing.invoices.open",
        order: 20,
      },
      {
        key: "invoicing.customers",
        label: "Customers",
        href: "/apps/invoicing",
        iconKey: "users",
        parentKey: "invoicing.root",
        actionKey: "invoicing.customers.open",
        order: 30,
      },
      {
        key: "invoicing.payments",
        label: "Payments",
        href: "/apps/invoicing",
        iconKey: "credit-card",
        parentKey: "invoicing.root",
        actionKey: "invoicing.payments.open",
        order: 40,
      },
      {
        key: "invoicing.reports",
        label: "Reports",
        href: "/apps/invoicing",
        iconKey: "bar-chart",
        parentKey: "invoicing.root",
        actionKey: "invoicing.reports.open",
        order: 50,
      },
    ],
    actions: [
      {
        key: "invoicing.open",
        name: "Open Invoicing",
        type: 'route',
        href: "/apps/invoicing",
        viewKeys: ["invoicing.dashboard"],
        target: 'current',
      },
      {
        key: "invoicing.invoices.open",
        name: "Open invoices",
        type: 'route',
        href: "/apps/invoicing",
        viewKeys: ["invoicing.invoice.list"],
        target: 'current',
      },
      {
        key: "invoicing.customers.open",
        name: "Open customers",
        type: 'route',
        href: "/apps/invoicing",
        viewKeys: ["invoicing.customer.list"],
        target: 'current',
      },
      {
        key: "invoicing.payments.open",
        name: "Open payments",
        type: 'route',
        href: "/apps/invoicing",
        viewKeys: ["invoicing.payment.list"],
        target: 'current',
      },
      {
        key: "invoicing.reports.open",
        name: "Open reports",
        type: 'report',
        href: "/apps/invoicing",
        viewKeys: ["invoicing.report.dashboard"],
        target: 'current',
      },
      {
        key: "invoicing.invoice.create",
        name: "Create invoice",
        type: 'wizard',
        resourceKey: "invoice",
        href: "/apps/invoicing",
        viewKeys: ["invoicing.invoice.form"],
        target: 'current',
      },
    ],
    views: [
      {
        key: "invoicing.dashboard",
        name: "Invoicing dashboard",
        type: 'dashboard',
        route: "/apps/invoicing",
        priority: 10,
      },
      {
        key: "invoicing.invoice.list",
        name: "Invoices",
        type: 'list',
        resourceKey: "invoice",
        route: "/apps/invoicing",
        priority: 20,
      },
      {
        key: "invoicing.invoice.form",
        name: "Invoice",
        type: 'form',
        resourceKey: "invoice",
        route: "/apps/invoicing",
        priority: 30,
      },
      {
        key: "invoicing.customer.list",
        name: "Customers",
        type: 'list',
        resourceKey: "customer",
        route: "/apps/invoicing",
        priority: 40,
      },
      {
        key: "invoicing.payment.list",
        name: "Payments",
        type: 'list',
        resourceKey: "payment",
        route: "/apps/invoicing",
        priority: 50,
      },
      {
        key: "invoicing.report.dashboard",
        name: "Receivables reports",
        type: 'dashboard',
        route: "/apps/invoicing",
        priority: 60,
      },
    ],
    resources: [
      {
        key: "invoice",
        label: "Invoice",
        table: "invoicing_invoices",
        companyScoped: true,
        ownerField: "created_by",
        permissions: {
          read: ["invoicing.invoice.view"],
          create: ["invoicing.invoice.create"],
          write: ["invoicing.invoice.edit"],
        },
        fields: [
          { key: "id", label: "ID", type: "string", readonly: true },
          { key: "company_id", label: "Company", type: "relation", readonly: true },
          { key: "customer_id", label: "Customer", type: "relation", required: true },
          { key: "invoice_number", label: "Invoice number", type: "string", readonly: true },
          { key: "status", label: "Status", type: "selection", readonly: true },
          { key: "invoice_date", label: "Invoice date", type: "date", required: true },
          { key: "due_date", label: "Due date", type: "date", required: true },
          { key: "currency", label: "Currency", type: "string", required: true },
          { key: "reference", label: "Reference", type: "string" },
          { key: "purchase_order_number", label: "PO number", type: "string" },
          { key: "total_amount", label: "Total", type: "money", readonly: true },
          { key: "notes", label: "Notes", type: "text" },
        ],
      },
      {
        key: "customer",
        label: "Billing customer",
        table: "invoicing_customers",
        companyScoped: true,
        ownerField: "created_by",
        permissions: {
          read: ["invoicing.customer.view"],
          create: ["invoicing.customer.manage"],
          write: ["invoicing.customer.manage"],
        },
        fields: [
          { key: "id", label: "ID", type: "string", readonly: true },
          { key: "company_id", label: "Company", type: "relation", readonly: true },
          { key: "name", label: "Name", type: "string", required: true },
          { key: "email", label: "Email", type: "string" },
          { key: "phone", label: "Phone", type: "string" },
          { key: "currency", label: "Currency", type: "string" },
          { key: "status", label: "Status", type: "selection" },
        ],
      },
      {
        key: "catalog_item",
        label: "Invoice item",
        table: "invoicing_catalog_items",
        companyScoped: true,
        ownerField: "created_by",
        permissions: {
          read: ["invoicing.catalog.view"],
          create: ["invoicing.catalog.manage"],
          write: ["invoicing.catalog.manage"],
        },
        fields: [
          { key: "id", label: "ID", type: "string", readonly: true },
          { key: "company_id", label: "Company", type: "relation", readonly: true },
          { key: "name", label: "Name", type: "string", required: true },
          { key: "sku", label: "SKU", type: "string" },
          { key: "unit_price", label: "Unit price", type: "money" },
        ],
      },
      {
        key: "payment",
        label: "Invoice payment",
        table: "invoicing_payments",
        companyScoped: true,
        ownerField: "created_by",
        permissions: {
          read: ["invoicing.payment.view"],
          create: ["invoicing.payment.record"],
          write: ["invoicing.payment.record"],
        },
        fields: [
          { key: "id", label: "ID", type: "string", readonly: true },
          { key: "company_id", label: "Company", type: "relation", readonly: true },
          { key: "payment_number", label: "Payment number", type: "string", readonly: true },
          { key: "amount", label: "Amount", type: "money", readonly: true },
          { key: "method", label: "Method", type: "selection", readonly: true },
        ],
      },
      {
        key: "credit_note",
        label: "Credit note",
        table: "invoicing_credit_notes",
        companyScoped: true,
        ownerField: "created_by",
        permissions: {
          read: ["invoicing.invoice.view"],
          create: ["invoicing.credit_note.manage"],
          write: ["invoicing.credit_note.manage"],
        },
      },
      {
        key: "recurring",
        label: "Recurring invoice",
        table: "invoicing_recurring_templates",
        companyScoped: true,
        ownerField: "created_by",
        permissions: {
          read: ["invoicing.invoice.view"],
          create: ["invoicing.recurring.manage"],
          write: ["invoicing.recurring.manage"],
        },
      },
      {
        key: "settings",
        label: "Invoicing settings",
        table: "invoicing_settings",
        companyScoped: true,
        ownerField: "updated_by",
        permissions: {
          read: ["invoicing.invoice.view"],
          write: ["invoicing.settings.manage"],
        },
      },
    ],
    security: {
      permissions: [
        { key: "invoicing.invoice.view", name: "View invoices", resource: "invoice", action: "view", scope: "company", defaultSystemRoles: ["admin","member"] },
        { key: "invoicing.invoice.create", name: "Create invoices", resource: "invoice", action: "create", scope: "company", defaultSystemRoles: ["admin","member"] },
        { key: "invoicing.invoice.edit", name: "Edit draft invoices", resource: "invoice", action: "edit", scope: "company", defaultSystemRoles: ["admin","member"] },
        { key: "invoicing.invoice.confirm", name: "Confirm invoices", resource: "invoice", action: "confirm", scope: "company", defaultSystemRoles: ["admin"] },
        { key: "invoicing.invoice.send", name: "Send invoices", resource: "invoice", action: "send", scope: "company", defaultSystemRoles: ["admin","member"] },
        { key: "invoicing.invoice.cancel", name: "Cancel or void invoices", resource: "invoice", action: "cancel", scope: "company", defaultSystemRoles: ["admin"] },
        { key: "invoicing.payment.view", name: "View invoice payments", resource: "payment", action: "view", scope: "company", defaultSystemRoles: ["admin","member"] },
        { key: "invoicing.payment.record", name: "Record invoice payments", resource: "payment", action: "record", scope: "company", defaultSystemRoles: ["admin"] },
        { key: "invoicing.credit_note.manage", name: "Manage credit notes", resource: "credit_note", action: "manage", scope: "company", defaultSystemRoles: ["admin"] },
        { key: "invoicing.customer.view", name: "View billing customers", resource: "customer", action: "view", scope: "company", defaultSystemRoles: ["admin","member"] },
        { key: "invoicing.customer.manage", name: "Manage billing customers", resource: "customer", action: "manage", scope: "company", defaultSystemRoles: ["admin","member"] },
        { key: "invoicing.catalog.view", name: "View invoice catalog", resource: "catalog_item", action: "view", scope: "company", defaultSystemRoles: ["admin","member"] },
        { key: "invoicing.catalog.manage", name: "Manage invoice catalog", resource: "catalog_item", action: "manage", scope: "company", defaultSystemRoles: ["admin"] },
        { key: "invoicing.recurring.manage", name: "Manage recurring invoices", resource: "recurring", action: "manage", scope: "company", defaultSystemRoles: ["admin"] },
        { key: "invoicing.report.view", name: "View invoicing reports", resource: "report", action: "view", scope: "company", defaultSystemRoles: ["admin","member"] },
        { key: "invoicing.settings.manage", name: "Manage invoicing settings", resource: "settings", action: "manage", scope: "company", defaultSystemRoles: ["admin"] },
      ],
      recordPolicies: [
        { key: "invoicing.invoice.company", name: "Invoices in current company", resourceKey: "invoice", operations: ["read","create","write"], scope: "company" },
        { key: "invoicing.customer.company", name: "Customers in current company", resourceKey: "customer", operations: ["read","create","write"], scope: "company" },
        { key: "invoicing.catalog.company", name: "Catalog in current company", resourceKey: "catalog_item", operations: ["read","create","write"], scope: "company" },
        { key: "invoicing.payment.company", name: "Payments in current company", resourceKey: "payment", operations: ["read","create","write"], scope: "company" },
        { key: "invoicing.credit.company", name: "Credit notes in current company", resourceKey: "credit_note", operations: ["read","create","write"], scope: "company" },
        { key: "invoicing.recurring.company", name: "Recurring invoices in current company", resourceKey: "recurring", operations: ["read","create","write"], scope: "company" },
        { key: "invoicing.settings.company", name: "Invoicing settings in current company", resourceKey: "settings", operations: ["read","write"], scope: "company" },
      ],
      fieldPolicies: [],
    },
    settings: [
      "general",
      "numbering",
      "taxes",
      "payment_terms",
      "templates",
      "payments",
      "delivery",
      "reminders",
      "recurring",
      "approvals",
    ],
    extensions: {
      dashboard: true,
      search: true,
      notifications: false,
      activity: true,
      automationTriggers: false,
      automationActions: false,
      aiTools: true,
      integrationProviders: false,
      apiEndpoints: false,
      dataExport: false,
      dataErasure: false,
    },
  }),

  defineSamiModule({
    key: "expenses",
    name: "Expenses",
    version: '1.0.0',
    description: "Record and manage business expenses.",
    category: "finance",
    icon: "file-text",
    route: "apps/expenses",
    application: true,
    installable: true,
    autoInstall: false,
    recommended: false,
    depends: [],
    optionalDepends: [],
    schemaPath: "lib/apps/expenses/schema.sql",
    migrationNamespace: "expenses",
    navigation: [
      {
        key: "expenses.root",
        label: "Expenses",
        href: "/apps/expenses",
        iconKey: "file-text",
        parentKey: null,
        actionKey: "expenses.open",
        order: 10,
      },
    ],
    actions: [
      {
        key: "expenses.open",
        name: "Open Expenses",
        type: 'route',
        href: "/apps/expenses",
        viewKeys: ["expenses.workspace"],
        target: 'current',
      },
    ],
    views: [
      {
        key: "expenses.workspace",
        name: "Expenses workspace",
        type: 'workspace',
        route: "/apps/expenses",
        priority: 10,
      },
    ],
    resources: [],
    security: {
      permissions: [],
      recordPolicies: [],
      fieldPolicies: [],
    },
    settings: [],
    extensions: {
      dashboard: false,
      search: false,
      notifications: false,
      activity: false,
      automationTriggers: false,
      automationActions: false,
      aiTools: false,
      integrationProviders: false,
      apiEndpoints: false,
      dataExport: false,
      dataErasure: false,
    },
  }),

  defineSamiModule({
    key: "spreadsheet",
    name: "Spreadsheet / BI",
    version: '1.0.0',
    description: "Analyze business data with AI-powered reports and spreadsheets.",
    category: "finance",
    icon: "bar-chart",
    route: "apps/spreadsheet",
    application: true,
    installable: true,
    autoInstall: false,
    recommended: false,
    depends: [],
    optionalDepends: [],
    schemaPath: "lib/apps/spreadsheet/schema.sql",
    migrationNamespace: "spreadsheet",
    navigation: [
      {
        key: "spreadsheet.root",
        label: "Spreadsheet / BI",
        href: "/apps/spreadsheet",
        iconKey: "bar-chart",
        parentKey: null,
        actionKey: "spreadsheet.open",
        order: 10,
      },
    ],
    actions: [
      {
        key: "spreadsheet.open",
        name: "Open Spreadsheet / BI",
        type: 'route',
        href: "/apps/spreadsheet",
        viewKeys: ["spreadsheet.workspace"],
        target: 'current',
      },
    ],
    views: [
      {
        key: "spreadsheet.workspace",
        name: "Spreadsheet / BI workspace",
        type: 'workspace',
        route: "/apps/spreadsheet",
        priority: 10,
      },
    ],
    resources: [],
    security: {
      permissions: [],
      recordPolicies: [],
      fieldPolicies: [],
    },
    settings: [],
    extensions: {
      dashboard: false,
      search: false,
      notifications: false,
      activity: false,
      automationTriggers: false,
      automationActions: false,
      aiTools: false,
      integrationProviders: false,
      apiEndpoints: false,
      dataExport: false,
      dataErasure: false,
    },
  }),

  defineSamiModule({
    key: "documents",
    name: "Documents",
    version: '1.0.0',
    description: "Store, organize and search business documents.",
    category: "documents",
    icon: "folder",
    route: "apps/documents",
    application: true,
    installable: true,
    autoInstall: false,
    recommended: false,
    depends: [],
    optionalDepends: [],
    schemaPath: "lib/apps/documents/schema.sql",
    migrationNamespace: "documents",
    navigation: [
      {
        key: "documents.root",
        label: "Documents",
        href: "/apps/documents",
        iconKey: "folder",
        parentKey: null,
        actionKey: "documents.open",
        order: 10,
      },
    ],
    actions: [
      {
        key: "documents.open",
        name: "Open Documents",
        type: 'route',
        href: "/apps/documents",
        viewKeys: ["documents.workspace"],
        target: 'current',
      },
    ],
    views: [
      {
        key: "documents.workspace",
        name: "Documents workspace",
        type: 'workspace',
        route: "/apps/documents",
        priority: 10,
      },
    ],
    resources: [],
    security: {
      permissions: [],
      recordPolicies: [],
      fieldPolicies: [],
    },
    settings: [],
    extensions: {
      dashboard: false,
      search: false,
      notifications: false,
      activity: false,
      automationTriggers: false,
      automationActions: false,
      aiTools: false,
      integrationProviders: false,
      apiEndpoints: false,
      dataExport: false,
      dataErasure: false,
    },
  }),

  defineSamiModule({
    key: "sign",
    name: "Sign",
    version: '1.0.0',
    description: "Send and manage documents that need signatures.",
    category: "documents",
    icon: "pen-tool",
    route: "apps/sign",
    application: true,
    installable: true,
    autoInstall: false,
    recommended: false,
    depends: [],
    optionalDepends: [],
    schemaPath: "lib/apps/sign/schema.sql",
    migrationNamespace: "sign",
    navigation: [
      {
        key: "sign.root",
        label: "Sign",
        href: "/apps/sign",
        iconKey: "pen-tool",
        parentKey: null,
        actionKey: "sign.open",
        order: 10,
      },
    ],
    actions: [
      {
        key: "sign.open",
        name: "Open Sign",
        type: 'route',
        href: "/apps/sign",
        viewKeys: ["sign.workspace"],
        target: 'current',
      },
    ],
    views: [
      {
        key: "sign.workspace",
        name: "Sign workspace",
        type: 'workspace',
        route: "/apps/sign",
        priority: 10,
      },
    ],
    resources: [],
    security: {
      permissions: [],
      recordPolicies: [],
      fieldPolicies: [],
    },
    settings: [],
    extensions: {
      dashboard: false,
      search: false,
      notifications: false,
      activity: false,
      automationTriggers: false,
      automationActions: false,
      aiTools: false,
      integrationProviders: false,
      apiEndpoints: false,
      dataExport: false,
      dataErasure: false,
    },
  }),

  defineSamiModule({
    key: "crm",
    name: "CRM",
    version: '1.0.0',
    description: "Manage leads, customers, opportunities and relationships.",
    category: "sales",
    icon: "users",
    route: "apps/crm",
    application: true,
    installable: true,
    autoInstall: false,
    recommended: true,
    depends: [],
    optionalDepends: [],
    schemaPath: "lib/apps/crm/schema.sql",
    migrationNamespace: "crm",
    navigation: [
      {
        key: "crm.root",
        label: "CRM",
        href: "/apps/crm",
        iconKey: "users",
        parentKey: null,
        actionKey: "crm.open",
        order: 10,
      },
    ],
    actions: [
      {
        key: "crm.open",
        name: "Open CRM",
        type: 'route',
        href: "/apps/crm",
        viewKeys: ["crm.workspace"],
        target: 'current',
      },
    ],
    views: [
      {
        key: "crm.workspace",
        name: "CRM workspace",
        type: 'workspace',
        route: "/apps/crm",
        priority: 10,
      },
    ],
    resources: [],
    security: {
      permissions: [],
      recordPolicies: [],
      fieldPolicies: [],
    },
    settings: [],
    extensions: {
      dashboard: false,
      search: false,
      notifications: false,
      activity: false,
      automationTriggers: false,
      automationActions: false,
      aiTools: false,
      integrationProviders: false,
      apiEndpoints: false,
      dataExport: false,
      dataErasure: false,
    },
  }),

  defineSamiModule({
    key: "sales",
    name: "Sales",
    version: '1.0.0',
    description: "Manage quotations, sales orders and customers.",
    category: "sales",
    icon: "shopping-cart",
    route: "apps/sales",
    application: true,
    installable: true,
    autoInstall: false,
    recommended: true,
    depends: [],
    optionalDepends: [],
    schemaPath: "lib/apps/sales/schema.sql",
    migrationNamespace: "sales",
    navigation: [
      {
        key: "sales.root",
        label: "Sales",
        href: "/apps/sales",
        iconKey: "shopping-cart",
        parentKey: null,
        actionKey: "sales.open",
        order: 10,
      },
    ],
    actions: [
      {
        key: "sales.open",
        name: "Open Sales",
        type: 'route',
        href: "/apps/sales",
        viewKeys: ["sales.workspace"],
        target: 'current',
      },
    ],
    views: [
      {
        key: "sales.workspace",
        name: "Sales workspace",
        type: 'workspace',
        route: "/apps/sales",
        priority: 10,
      },
    ],
    resources: [],
    security: {
      permissions: [],
      recordPolicies: [],
      fieldPolicies: [],
    },
    settings: [],
    extensions: {
      dashboard: false,
      search: false,
      notifications: false,
      activity: false,
      automationTriggers: false,
      automationActions: false,
      aiTools: false,
      integrationProviders: false,
      apiEndpoints: false,
      dataExport: false,
      dataErasure: false,
    },
  }),

  defineSamiModule({
    key: "subscriptions",
    name: "Subscriptions",
    version: '1.0.0',
    description: "Manage recurring customers and subscription billing.",
    category: "sales",
    icon: "repeat",
    route: "apps/subscriptions",
    application: true,
    installable: true,
    autoInstall: false,
    recommended: false,
    depends: [],
    optionalDepends: [],
    schemaPath: "lib/apps/subscriptions/schema.sql",
    migrationNamespace: "subscriptions",
    navigation: [
      {
        key: "subscriptions.root",
        label: "Subscriptions",
        href: "/apps/subscriptions",
        iconKey: "repeat",
        parentKey: null,
        actionKey: "subscriptions.open",
        order: 10,
      },
    ],
    actions: [
      {
        key: "subscriptions.open",
        name: "Open Subscriptions",
        type: 'route',
        href: "/apps/subscriptions",
        viewKeys: ["subscriptions.workspace"],
        target: 'current',
      },
    ],
    views: [
      {
        key: "subscriptions.workspace",
        name: "Subscriptions workspace",
        type: 'workspace',
        route: "/apps/subscriptions",
        priority: 10,
      },
    ],
    resources: [],
    security: {
      permissions: [],
      recordPolicies: [],
      fieldPolicies: [],
    },
    settings: [],
    extensions: {
      dashboard: false,
      search: false,
      notifications: false,
      activity: false,
      automationTriggers: false,
      automationActions: false,
      aiTools: false,
      integrationProviders: false,
      apiEndpoints: false,
      dataExport: false,
      dataErasure: false,
    },
  }),

  defineSamiModule({
    key: "rentals",
    name: "Rentals",
    version: '1.0.0',
    description: "Manage rental products, contracts and returns.",
    category: "sales",
    icon: "home",
    route: "apps/rentals",
    application: true,
    installable: true,
    autoInstall: false,
    recommended: false,
    depends: [],
    optionalDepends: [],
    schemaPath: "lib/apps/rentals/schema.sql",
    migrationNamespace: "rentals",
    navigation: [
      {
        key: "rentals.root",
        label: "Rentals",
        href: "/apps/rentals",
        iconKey: "home",
        parentKey: null,
        actionKey: "rentals.open",
        order: 10,
      },
    ],
    actions: [
      {
        key: "rentals.open",
        name: "Open Rentals",
        type: 'route',
        href: "/apps/rentals",
        viewKeys: ["rentals.workspace"],
        target: 'current',
      },
    ],
    views: [
      {
        key: "rentals.workspace",
        name: "Rentals workspace",
        type: 'workspace',
        route: "/apps/rentals",
        priority: 10,
      },
    ],
    resources: [],
    security: {
      permissions: [],
      recordPolicies: [],
      fieldPolicies: [],
    },
    settings: [],
    extensions: {
      dashboard: false,
      search: false,
      notifications: false,
      activity: false,
      automationTriggers: false,
      automationActions: false,
      aiTools: false,
      integrationProviders: false,
      apiEndpoints: false,
      dataExport: false,
      dataErasure: false,
    },
  }),

  defineSamiModule({
    key: "pos_shop",
    name: "POS Shop",
    version: '1.0.0',
    description: "Run a retail point of sale.",
    category: "commerce",
    icon: "store",
    route: "apps/pos_shop",
    application: true,
    installable: true,
    autoInstall: false,
    recommended: false,
    depends: [],
    optionalDepends: [],
    schemaPath: "lib/apps/pos_shop/schema.sql",
    migrationNamespace: "pos_shop",
    navigation: [
      {
        key: "pos_shop.root",
        label: "POS Shop",
        href: "/apps/pos_shop",
        iconKey: "store",
        parentKey: null,
        actionKey: "pos_shop.open",
        order: 10,
      },
    ],
    actions: [
      {
        key: "pos_shop.open",
        name: "Open POS Shop",
        type: 'route',
        href: "/apps/pos_shop",
        viewKeys: ["pos_shop.workspace"],
        target: 'current',
      },
    ],
    views: [
      {
        key: "pos_shop.workspace",
        name: "POS Shop workspace",
        type: 'workspace',
        route: "/apps/pos_shop",
        priority: 10,
      },
    ],
    resources: [],
    security: {
      permissions: [],
      recordPolicies: [],
      fieldPolicies: [],
    },
    settings: [],
    extensions: {
      dashboard: false,
      search: false,
      notifications: false,
      activity: false,
      automationTriggers: false,
      automationActions: false,
      aiTools: false,
      integrationProviders: false,
      apiEndpoints: false,
      dataExport: false,
      dataErasure: false,
    },
  }),

  defineSamiModule({
    key: "pos_restaurant",
    name: "POS Restaurant",
    version: '1.0.0',
    description: "Run restaurant orders and point-of-sale operations.",
    category: "commerce",
    icon: "utensils",
    route: "apps/pos_restaurant",
    application: true,
    installable: true,
    autoInstall: false,
    recommended: false,
    depends: [],
    optionalDepends: [],
    schemaPath: "lib/apps/pos_restaurant/schema.sql",
    migrationNamespace: "pos_restaurant",
    navigation: [
      {
        key: "pos_restaurant.root",
        label: "POS Restaurant",
        href: "/apps/pos_restaurant",
        iconKey: "utensils",
        parentKey: null,
        actionKey: "pos_restaurant.open",
        order: 10,
      },
    ],
    actions: [
      {
        key: "pos_restaurant.open",
        name: "Open POS Restaurant",
        type: 'route',
        href: "/apps/pos_restaurant",
        viewKeys: ["pos_restaurant.workspace"],
        target: 'current',
      },
    ],
    views: [
      {
        key: "pos_restaurant.workspace",
        name: "POS Restaurant workspace",
        type: 'workspace',
        route: "/apps/pos_restaurant",
        priority: 10,
      },
    ],
    resources: [],
    security: {
      permissions: [],
      recordPolicies: [],
      fieldPolicies: [],
    },
    settings: [],
    extensions: {
      dashboard: false,
      search: false,
      notifications: false,
      activity: false,
      automationTriggers: false,
      automationActions: false,
      aiTools: false,
      integrationProviders: false,
      apiEndpoints: false,
      dataExport: false,
      dataErasure: false,
    },
  }),

  defineSamiModule({
    key: "inventory",
    name: "Inventory",
    version: '1.0.0',
    description: "Manage products, stock, warehouses and movements.",
    category: "supply_chain",
    icon: "package",
    route: "apps/inventory",
    application: true,
    installable: true,
    autoInstall: false,
    recommended: false,
    depends: [],
    optionalDepends: [],
    schemaPath: "lib/apps/inventory/schema.sql",
    migrationNamespace: "inventory",
    navigation: [
      {
        key: "inventory.root",
        label: "Inventory",
        href: "/apps/inventory",
        iconKey: "package",
        parentKey: null,
        actionKey: "inventory.open",
        order: 10,
      },
    ],
    actions: [
      {
        key: "inventory.open",
        name: "Open Inventory",
        type: 'route',
        href: "/apps/inventory",
        viewKeys: ["inventory.workspace"],
        target: 'current',
      },
    ],
    views: [
      {
        key: "inventory.workspace",
        name: "Inventory workspace",
        type: 'workspace',
        route: "/apps/inventory",
        priority: 10,
      },
    ],
    resources: [],
    security: {
      permissions: [],
      recordPolicies: [],
      fieldPolicies: [],
    },
    settings: [],
    extensions: {
      dashboard: false,
      search: false,
      notifications: false,
      activity: false,
      automationTriggers: false,
      automationActions: false,
      aiTools: false,
      integrationProviders: false,
      apiEndpoints: false,
      dataExport: false,
      dataErasure: false,
    },
  }),

  defineSamiModule({
    key: "manufacturing",
    name: "Manufacturing",
    version: '1.0.0',
    description: "Manage production, bills of materials and manufacturing orders.",
    category: "supply_chain",
    icon: "factory",
    route: "apps/manufacturing",
    application: true,
    installable: true,
    autoInstall: false,
    recommended: false,
    depends: [],
    optionalDepends: [],
    schemaPath: "lib/apps/manufacturing/schema.sql",
    migrationNamespace: "manufacturing",
    navigation: [
      {
        key: "manufacturing.root",
        label: "Manufacturing",
        href: "/apps/manufacturing",
        iconKey: "factory",
        parentKey: null,
        actionKey: "manufacturing.open",
        order: 10,
      },
    ],
    actions: [
      {
        key: "manufacturing.open",
        name: "Open Manufacturing",
        type: 'route',
        href: "/apps/manufacturing",
        viewKeys: ["manufacturing.workspace"],
        target: 'current',
      },
    ],
    views: [
      {
        key: "manufacturing.workspace",
        name: "Manufacturing workspace",
        type: 'workspace',
        route: "/apps/manufacturing",
        priority: 10,
      },
    ],
    resources: [],
    security: {
      permissions: [],
      recordPolicies: [],
      fieldPolicies: [],
    },
    settings: [],
    extensions: {
      dashboard: false,
      search: false,
      notifications: false,
      activity: false,
      automationTriggers: false,
      automationActions: false,
      aiTools: false,
      integrationProviders: false,
      apiEndpoints: false,
      dataExport: false,
      dataErasure: false,
    },
  }),

  defineSamiModule({
    key: "plm",
    name: "PLM",
    version: '1.0.0',
    description: "Manage product lifecycle and engineering changes.",
    category: "supply_chain",
    icon: "boxes",
    route: "apps/plm",
    application: true,
    installable: true,
    autoInstall: false,
    recommended: false,
    depends: [],
    optionalDepends: [],
    schemaPath: "lib/apps/plm/schema.sql",
    migrationNamespace: "plm",
    navigation: [
      {
        key: "plm.root",
        label: "PLM",
        href: "/apps/plm",
        iconKey: "boxes",
        parentKey: null,
        actionKey: "plm.open",
        order: 10,
      },
    ],
    actions: [
      {
        key: "plm.open",
        name: "Open PLM",
        type: 'route',
        href: "/apps/plm",
        viewKeys: ["plm.workspace"],
        target: 'current',
      },
    ],
    views: [
      {
        key: "plm.workspace",
        name: "PLM workspace",
        type: 'workspace',
        route: "/apps/plm",
        priority: 10,
      },
    ],
    resources: [],
    security: {
      permissions: [],
      recordPolicies: [],
      fieldPolicies: [],
    },
    settings: [],
    extensions: {
      dashboard: false,
      search: false,
      notifications: false,
      activity: false,
      automationTriggers: false,
      automationActions: false,
      aiTools: false,
      integrationProviders: false,
      apiEndpoints: false,
      dataExport: false,
      dataErasure: false,
    },
  }),

  defineSamiModule({
    key: "purchase",
    name: "Purchase",
    version: '1.0.0',
    description: "Manage suppliers, purchase orders and procurement.",
    category: "supply_chain",
    icon: "shopping-bag",
    route: "apps/purchase",
    application: true,
    installable: true,
    autoInstall: false,
    recommended: false,
    depends: [],
    optionalDepends: [],
    schemaPath: "lib/apps/purchase/schema.sql",
    migrationNamespace: "purchase",
    navigation: [
      {
        key: "purchase.root",
        label: "Purchase",
        href: "/apps/purchase",
        iconKey: "shopping-bag",
        parentKey: null,
        actionKey: "purchase.open",
        order: 10,
      },
    ],
    actions: [
      {
        key: "purchase.open",
        name: "Open Purchase",
        type: 'route',
        href: "/apps/purchase",
        viewKeys: ["purchase.workspace"],
        target: 'current',
      },
    ],
    views: [
      {
        key: "purchase.workspace",
        name: "Purchase workspace",
        type: 'workspace',
        route: "/apps/purchase",
        priority: 10,
      },
    ],
    resources: [],
    security: {
      permissions: [],
      recordPolicies: [],
      fieldPolicies: [],
    },
    settings: [],
    extensions: {
      dashboard: false,
      search: false,
      notifications: false,
      activity: false,
      automationTriggers: false,
      automationActions: false,
      aiTools: false,
      integrationProviders: false,
      apiEndpoints: false,
      dataExport: false,
      dataErasure: false,
    },
  }),

  defineSamiModule({
    key: "maintenance",
    name: "Maintenance",
    version: '1.0.0',
    description: "Track equipment and maintenance activities.",
    category: "operations",
    icon: "wrench",
    route: "apps/maintenance",
    application: true,
    installable: true,
    autoInstall: false,
    recommended: false,
    depends: [],
    optionalDepends: [],
    schemaPath: "lib/apps/maintenance/schema.sql",
    migrationNamespace: "maintenance",
    navigation: [
      {
        key: "maintenance.root",
        label: "Maintenance",
        href: "/apps/maintenance",
        iconKey: "wrench",
        parentKey: null,
        actionKey: "maintenance.open",
        order: 10,
      },
    ],
    actions: [
      {
        key: "maintenance.open",
        name: "Open Maintenance",
        type: 'route',
        href: "/apps/maintenance",
        viewKeys: ["maintenance.workspace"],
        target: 'current',
      },
    ],
    views: [
      {
        key: "maintenance.workspace",
        name: "Maintenance workspace",
        type: 'workspace',
        route: "/apps/maintenance",
        priority: 10,
      },
    ],
    resources: [],
    security: {
      permissions: [],
      recordPolicies: [],
      fieldPolicies: [],
    },
    settings: [],
    extensions: {
      dashboard: false,
      search: false,
      notifications: false,
      activity: false,
      automationTriggers: false,
      automationActions: false,
      aiTools: false,
      integrationProviders: false,
      apiEndpoints: false,
      dataExport: false,
      dataErasure: false,
    },
  }),

  defineSamiModule({
    key: "quality",
    name: "Quality",
    version: '1.0.0',
    description: "Manage quality checks, controls and issues.",
    category: "operations",
    icon: "shield-check",
    route: "apps/quality",
    application: true,
    installable: true,
    autoInstall: false,
    recommended: false,
    depends: [],
    optionalDepends: [],
    schemaPath: "lib/apps/quality/schema.sql",
    migrationNamespace: "quality",
    navigation: [
      {
        key: "quality.root",
        label: "Quality",
        href: "/apps/quality",
        iconKey: "shield-check",
        parentKey: null,
        actionKey: "quality.open",
        order: 10,
      },
    ],
    actions: [
      {
        key: "quality.open",
        name: "Open Quality",
        type: 'route',
        href: "/apps/quality",
        viewKeys: ["quality.workspace"],
        target: 'current',
      },
    ],
    views: [
      {
        key: "quality.workspace",
        name: "Quality workspace",
        type: 'workspace',
        route: "/apps/quality",
        priority: 10,
      },
    ],
    resources: [],
    security: {
      permissions: [],
      recordPolicies: [],
      fieldPolicies: [],
    },
    settings: [],
    extensions: {
      dashboard: false,
      search: false,
      notifications: false,
      activity: false,
      automationTriggers: false,
      automationActions: false,
      aiTools: false,
      integrationProviders: false,
      apiEndpoints: false,
      dataExport: false,
      dataErasure: false,
    },
  }),

  defineSamiModule({
    key: "employees",
    name: "Employees",
    version: '1.0.0',
    description: "Manage employees and workforce information.",
    category: "people",
    icon: "user-round",
    route: "apps/employees",
    application: true,
    installable: true,
    autoInstall: false,
    recommended: false,
    depends: [],
    optionalDepends: [],
    schemaPath: "lib/apps/employees/schema.sql",
    migrationNamespace: "employees",
    navigation: [
      {
        key: "employees.root",
        label: "Employees",
        href: "/apps/employees",
        iconKey: "user-round",
        parentKey: null,
        actionKey: "employees.open",
        order: 10,
      },
    ],
    actions: [
      {
        key: "employees.open",
        name: "Open Employees",
        type: 'route',
        href: "/apps/employees",
        viewKeys: ["employees.workspace"],
        target: 'current',
      },
    ],
    views: [
      {
        key: "employees.workspace",
        name: "Employees workspace",
        type: 'workspace',
        route: "/apps/employees",
        priority: 10,
      },
    ],
    resources: [],
    security: {
      permissions: [],
      recordPolicies: [],
      fieldPolicies: [],
    },
    settings: [],
    extensions: {
      dashboard: false,
      search: false,
      notifications: false,
      activity: false,
      automationTriggers: false,
      automationActions: false,
      aiTools: false,
      integrationProviders: false,
      apiEndpoints: false,
      dataExport: false,
      dataErasure: false,
    },
  }),

  defineSamiModule({
    key: "fleet",
    name: "Fleet",
    version: '1.0.0',
    description: "Manage company vehicles and fleet operations.",
    category: "people",
    icon: "car",
    route: "apps/fleet",
    application: true,
    installable: true,
    autoInstall: false,
    recommended: false,
    depends: [],
    optionalDepends: [],
    schemaPath: "lib/apps/fleet/schema.sql",
    migrationNamespace: "fleet",
    navigation: [
      {
        key: "fleet.root",
        label: "Fleet",
        href: "/apps/fleet",
        iconKey: "car",
        parentKey: null,
        actionKey: "fleet.open",
        order: 10,
      },
    ],
    actions: [
      {
        key: "fleet.open",
        name: "Open Fleet",
        type: 'route',
        href: "/apps/fleet",
        viewKeys: ["fleet.workspace"],
        target: 'current',
      },
    ],
    views: [
      {
        key: "fleet.workspace",
        name: "Fleet workspace",
        type: 'workspace',
        route: "/apps/fleet",
        priority: 10,
      },
    ],
    resources: [],
    security: {
      permissions: [],
      recordPolicies: [],
      fieldPolicies: [],
    },
    settings: [],
    extensions: {
      dashboard: false,
      search: false,
      notifications: false,
      activity: false,
      automationTriggers: false,
      automationActions: false,
      aiTools: false,
      integrationProviders: false,
      apiEndpoints: false,
      dataExport: false,
      dataErasure: false,
    },
  }),

  defineSamiModule({
    key: "referrals",
    name: "Referrals",
    version: '1.0.0',
    description: "Manage employee referral programs.",
    category: "people",
    icon: "user-plus",
    route: "apps/referrals",
    application: true,
    installable: true,
    autoInstall: false,
    recommended: false,
    depends: [],
    optionalDepends: [],
    schemaPath: "lib/apps/referrals/schema.sql",
    migrationNamespace: "referrals",
    navigation: [
      {
        key: "referrals.root",
        label: "Referrals",
        href: "/apps/referrals",
        iconKey: "user-plus",
        parentKey: null,
        actionKey: "referrals.open",
        order: 10,
      },
    ],
    actions: [
      {
        key: "referrals.open",
        name: "Open Referrals",
        type: 'route',
        href: "/apps/referrals",
        viewKeys: ["referrals.workspace"],
        target: 'current',
      },
    ],
    views: [
      {
        key: "referrals.workspace",
        name: "Referrals workspace",
        type: 'workspace',
        route: "/apps/referrals",
        priority: 10,
      },
    ],
    resources: [],
    security: {
      permissions: [],
      recordPolicies: [],
      fieldPolicies: [],
    },
    settings: [],
    extensions: {
      dashboard: false,
      search: false,
      notifications: false,
      activity: false,
      automationTriggers: false,
      automationActions: false,
      aiTools: false,
      integrationProviders: false,
      apiEndpoints: false,
      dataExport: false,
      dataErasure: false,
    },
  }),

  defineSamiModule({
    key: "appraisals",
    name: "Appraisals",
    version: '1.0.0',
    description: "Manage employee performance reviews.",
    category: "people",
    icon: "clipboard-check",
    route: "apps/appraisals",
    application: true,
    installable: true,
    autoInstall: false,
    recommended: false,
    depends: [],
    optionalDepends: [],
    schemaPath: "lib/apps/appraisals/schema.sql",
    migrationNamespace: "appraisals",
    navigation: [
      {
        key: "appraisals.root",
        label: "Appraisals",
        href: "/apps/appraisals",
        iconKey: "clipboard-check",
        parentKey: null,
        actionKey: "appraisals.open",
        order: 10,
      },
    ],
    actions: [
      {
        key: "appraisals.open",
        name: "Open Appraisals",
        type: 'route',
        href: "/apps/appraisals",
        viewKeys: ["appraisals.workspace"],
        target: 'current',
      },
    ],
    views: [
      {
        key: "appraisals.workspace",
        name: "Appraisals workspace",
        type: 'workspace',
        route: "/apps/appraisals",
        priority: 10,
      },
    ],
    resources: [],
    security: {
      permissions: [],
      recordPolicies: [],
      fieldPolicies: [],
    },
    settings: [],
    extensions: {
      dashboard: false,
      search: false,
      notifications: false,
      activity: false,
      automationTriggers: false,
      automationActions: false,
      aiTools: false,
      integrationProviders: false,
      apiEndpoints: false,
      dataExport: false,
      dataErasure: false,
    },
  }),

  defineSamiModule({
    key: "time_off",
    name: "Time Off",
    version: '1.0.0',
    description: "Manage leave and time-off requests.",
    category: "people",
    icon: "calendar-off",
    route: "apps/time_off",
    application: true,
    installable: true,
    autoInstall: false,
    recommended: false,
    depends: [],
    optionalDepends: [],
    schemaPath: "lib/apps/time_off/schema.sql",
    migrationNamespace: "time_off",
    navigation: [
      {
        key: "time_off.root",
        label: "Time Off",
        href: "/apps/time_off",
        iconKey: "calendar-off",
        parentKey: null,
        actionKey: "time_off.open",
        order: 10,
      },
    ],
    actions: [
      {
        key: "time_off.open",
        name: "Open Time Off",
        type: 'route',
        href: "/apps/time_off",
        viewKeys: ["time_off.workspace"],
        target: 'current',
      },
    ],
    views: [
      {
        key: "time_off.workspace",
        name: "Time Off workspace",
        type: 'workspace',
        route: "/apps/time_off",
        priority: 10,
      },
    ],
    resources: [],
    security: {
      permissions: [],
      recordPolicies: [],
      fieldPolicies: [],
    },
    settings: [],
    extensions: {
      dashboard: false,
      search: false,
      notifications: false,
      activity: false,
      automationTriggers: false,
      automationActions: false,
      aiTools: false,
      integrationProviders: false,
      apiEndpoints: false,
      dataExport: false,
      dataErasure: false,
    },
  }),

  defineSamiModule({
    key: "recruitment",
    name: "Recruitment",
    version: '1.0.0',
    description: "Manage vacancies, applicants and hiring.",
    category: "people",
    icon: "user-search",
    route: "apps/recruitment",
    application: true,
    installable: true,
    autoInstall: false,
    recommended: false,
    depends: [],
    optionalDepends: [],
    schemaPath: "lib/apps/recruitment/schema.sql",
    migrationNamespace: "recruitment",
    navigation: [
      {
        key: "recruitment.root",
        label: "Recruitment",
        href: "/apps/recruitment",
        iconKey: "user-search",
        parentKey: null,
        actionKey: "recruitment.open",
        order: 10,
      },
    ],
    actions: [
      {
        key: "recruitment.open",
        name: "Open Recruitment",
        type: 'route',
        href: "/apps/recruitment",
        viewKeys: ["recruitment.workspace"],
        target: 'current',
      },
    ],
    views: [
      {
        key: "recruitment.workspace",
        name: "Recruitment workspace",
        type: 'workspace',
        route: "/apps/recruitment",
        priority: 10,
      },
    ],
    resources: [],
    security: {
      permissions: [],
      recordPolicies: [],
      fieldPolicies: [],
    },
    settings: [],
    extensions: {
      dashboard: false,
      search: false,
      notifications: false,
      activity: false,
      automationTriggers: false,
      automationActions: false,
      aiTools: false,
      integrationProviders: false,
      apiEndpoints: false,
      dataExport: false,
      dataErasure: false,
    },
  }),

  defineSamiModule({
    key: "social_marketing",
    name: "Social Marketing",
    version: '1.0.0',
    description: "Plan and manage social media marketing.",
    category: "marketing",
    icon: "megaphone",
    route: "apps/social_marketing",
    application: true,
    installable: true,
    autoInstall: false,
    recommended: false,
    depends: [],
    optionalDepends: [],
    schemaPath: "lib/apps/social_marketing/schema.sql",
    migrationNamespace: "social_marketing",
    navigation: [
      {
        key: "social_marketing.root",
        label: "Social Marketing",
        href: "/apps/social_marketing",
        iconKey: "megaphone",
        parentKey: null,
        actionKey: "social_marketing.open",
        order: 10,
      },
    ],
    actions: [
      {
        key: "social_marketing.open",
        name: "Open Social Marketing",
        type: 'route',
        href: "/apps/social_marketing",
        viewKeys: ["social_marketing.workspace"],
        target: 'current',
      },
    ],
    views: [
      {
        key: "social_marketing.workspace",
        name: "Social Marketing workspace",
        type: 'workspace',
        route: "/apps/social_marketing",
        priority: 10,
      },
    ],
    resources: [],
    security: {
      permissions: [],
      recordPolicies: [],
      fieldPolicies: [],
    },
    settings: [],
    extensions: {
      dashboard: false,
      search: false,
      notifications: false,
      activity: false,
      automationTriggers: false,
      automationActions: false,
      aiTools: false,
      integrationProviders: false,
      apiEndpoints: false,
      dataExport: false,
      dataErasure: false,
    },
  }),

  defineSamiModule({
    key: "email_marketing",
    name: "Email Marketing",
    version: '1.0.0',
    description: "Create and manage email campaigns.",
    category: "marketing",
    icon: "mail",
    route: "apps/email_marketing",
    application: true,
    installable: true,
    autoInstall: false,
    recommended: false,
    depends: [],
    optionalDepends: [],
    schemaPath: "lib/apps/email_marketing/schema.sql",
    migrationNamespace: "email_marketing",
    navigation: [
      {
        key: "email_marketing.root",
        label: "Email Marketing",
        href: "/apps/email_marketing",
        iconKey: "mail",
        parentKey: null,
        actionKey: "email_marketing.open",
        order: 10,
      },
    ],
    actions: [
      {
        key: "email_marketing.open",
        name: "Open Email Marketing",
        type: 'route',
        href: "/apps/email_marketing",
        viewKeys: ["email_marketing.workspace"],
        target: 'current',
      },
    ],
    views: [
      {
        key: "email_marketing.workspace",
        name: "Email Marketing workspace",
        type: 'workspace',
        route: "/apps/email_marketing",
        priority: 10,
      },
    ],
    resources: [],
    security: {
      permissions: [],
      recordPolicies: [],
      fieldPolicies: [],
    },
    settings: [],
    extensions: {
      dashboard: false,
      search: false,
      notifications: false,
      activity: false,
      automationTriggers: false,
      automationActions: false,
      aiTools: false,
      integrationProviders: false,
      apiEndpoints: false,
      dataExport: false,
      dataErasure: false,
    },
  }),

  defineSamiModule({
    key: "sms_marketing",
    name: "SMS Marketing",
    version: '1.0.0',
    description: "Create and manage SMS campaigns.",
    category: "marketing",
    icon: "message-square",
    route: "apps/sms_marketing",
    application: true,
    installable: true,
    autoInstall: false,
    recommended: false,
    depends: [],
    optionalDepends: [],
    schemaPath: "lib/apps/sms_marketing/schema.sql",
    migrationNamespace: "sms_marketing",
    navigation: [
      {
        key: "sms_marketing.root",
        label: "SMS Marketing",
        href: "/apps/sms_marketing",
        iconKey: "message-square",
        parentKey: null,
        actionKey: "sms_marketing.open",
        order: 10,
      },
    ],
    actions: [
      {
        key: "sms_marketing.open",
        name: "Open SMS Marketing",
        type: 'route',
        href: "/apps/sms_marketing",
        viewKeys: ["sms_marketing.workspace"],
        target: 'current',
      },
    ],
    views: [
      {
        key: "sms_marketing.workspace",
        name: "SMS Marketing workspace",
        type: 'workspace',
        route: "/apps/sms_marketing",
        priority: 10,
      },
    ],
    resources: [],
    security: {
      permissions: [],
      recordPolicies: [],
      fieldPolicies: [],
    },
    settings: [],
    extensions: {
      dashboard: false,
      search: false,
      notifications: false,
      activity: false,
      automationTriggers: false,
      automationActions: false,
      aiTools: false,
      integrationProviders: false,
      apiEndpoints: false,
      dataExport: false,
      dataErasure: false,
    },
  }),

  defineSamiModule({
    key: "events",
    name: "Events",
    version: '1.0.0',
    description: "Manage events, registrations and attendees.",
    category: "marketing",
    icon: "calendar-days",
    route: "apps/events",
    application: true,
    installable: true,
    autoInstall: false,
    recommended: false,
    depends: [],
    optionalDepends: [],
    schemaPath: "lib/apps/events/schema.sql",
    migrationNamespace: "events",
    navigation: [
      {
        key: "events.root",
        label: "Events",
        href: "/apps/events",
        iconKey: "calendar-days",
        parentKey: null,
        actionKey: "events.open",
        order: 10,
      },
    ],
    actions: [
      {
        key: "events.open",
        name: "Open Events",
        type: 'route',
        href: "/apps/events",
        viewKeys: ["events.workspace"],
        target: 'current',
      },
    ],
    views: [
      {
        key: "events.workspace",
        name: "Events workspace",
        type: 'workspace',
        route: "/apps/events",
        priority: 10,
      },
    ],
    resources: [],
    security: {
      permissions: [],
      recordPolicies: [],
      fieldPolicies: [],
    },
    settings: [],
    extensions: {
      dashboard: false,
      search: false,
      notifications: false,
      activity: false,
      automationTriggers: false,
      automationActions: false,
      aiTools: false,
      integrationProviders: false,
      apiEndpoints: false,
      dataExport: false,
      dataErasure: false,
    },
  }),

  defineSamiModule({
    key: "marketing_automation",
    name: "Marketing Automation",
    version: '1.0.0',
    description: "Automate campaigns and customer journeys.",
    category: "marketing",
    icon: "workflow",
    route: "apps/marketing_automation",
    application: true,
    installable: true,
    autoInstall: false,
    recommended: false,
    depends: [],
    optionalDepends: [],
    schemaPath: "lib/apps/marketing_automation/schema.sql",
    migrationNamespace: "marketing_automation",
    navigation: [
      {
        key: "marketing_automation.root",
        label: "Marketing Automation",
        href: "/apps/marketing_automation",
        iconKey: "workflow",
        parentKey: null,
        actionKey: "marketing_automation.open",
        order: 10,
      },
    ],
    actions: [
      {
        key: "marketing_automation.open",
        name: "Open Marketing Automation",
        type: 'route',
        href: "/apps/marketing_automation",
        viewKeys: ["marketing_automation.workspace"],
        target: 'current',
      },
    ],
    views: [
      {
        key: "marketing_automation.workspace",
        name: "Marketing Automation workspace",
        type: 'workspace',
        route: "/apps/marketing_automation",
        priority: 10,
      },
    ],
    resources: [],
    security: {
      permissions: [],
      recordPolicies: [],
      fieldPolicies: [],
    },
    settings: [],
    extensions: {
      dashboard: false,
      search: false,
      notifications: false,
      activity: false,
      automationTriggers: false,
      automationActions: false,
      aiTools: false,
      integrationProviders: false,
      apiEndpoints: false,
      dataExport: false,
      dataErasure: false,
    },
  }),

  defineSamiModule({
    key: "surveys",
    name: "Surveys",
    version: '1.0.0',
    description: "Create surveys and collect responses.",
    category: "marketing",
    icon: "clipboard-list",
    route: "apps/surveys",
    application: true,
    installable: true,
    autoInstall: false,
    recommended: false,
    depends: [],
    optionalDepends: [],
    schemaPath: "lib/apps/surveys/schema.sql",
    migrationNamespace: "surveys",
    navigation: [
      {
        key: "surveys.root",
        label: "Surveys",
        href: "/apps/surveys",
        iconKey: "clipboard-list",
        parentKey: null,
        actionKey: "surveys.open",
        order: 10,
      },
    ],
    actions: [
      {
        key: "surveys.open",
        name: "Open Surveys",
        type: 'route',
        href: "/apps/surveys",
        viewKeys: ["surveys.workspace"],
        target: 'current',
      },
    ],
    views: [
      {
        key: "surveys.workspace",
        name: "Surveys workspace",
        type: 'workspace',
        route: "/apps/surveys",
        priority: 10,
      },
    ],
    resources: [],
    security: {
      permissions: [],
      recordPolicies: [],
      fieldPolicies: [],
    },
    settings: [],
    extensions: {
      dashboard: false,
      search: false,
      notifications: false,
      activity: false,
      automationTriggers: false,
      automationActions: false,
      aiTools: false,
      integrationProviders: false,
      apiEndpoints: false,
      dataExport: false,
      dataErasure: false,
    },
  }),

  defineSamiModule({
    key: "projects",
    name: "Projects",
    version: '1.0.0',
    description: "Plan projects, tasks and team work.",
    category: "work",
    icon: "briefcase",
    route: "apps/projects",
    application: true,
    installable: true,
    autoInstall: false,
    recommended: true,
    depends: [],
    optionalDepends: [],
    schemaPath: "lib/apps/projects/schema.sql",
    migrationNamespace: "projects",
    navigation: [
      {
        key: "projects.root",
        label: "Projects",
        href: "/apps/projects",
        iconKey: "briefcase",
        parentKey: null,
        actionKey: "projects.open",
        order: 10,
      },
    ],
    actions: [
      {
        key: "projects.open",
        name: "Open Projects",
        type: 'route',
        href: "/apps/projects",
        viewKeys: ["projects.workspace"],
        target: 'current',
      },
    ],
    views: [
      {
        key: "projects.workspace",
        name: "Projects workspace",
        type: 'workspace',
        route: "/apps/projects",
        priority: 10,
      },
    ],
    resources: [],
    security: {
      permissions: [],
      recordPolicies: [],
      fieldPolicies: [],
    },
    settings: [],
    extensions: {
      dashboard: false,
      search: false,
      notifications: false,
      activity: false,
      automationTriggers: false,
      automationActions: false,
      aiTools: false,
      integrationProviders: false,
      apiEndpoints: false,
      dataExport: false,
      dataErasure: false,
    },
  }),

  defineSamiModule({
    key: "timesheets",
    name: "Timesheets",
    version: '1.0.0',
    description: "Track time spent on work and projects.",
    category: "work",
    icon: "clock",
    route: "apps/timesheets",
    application: true,
    installable: true,
    autoInstall: false,
    recommended: false,
    depends: [],
    optionalDepends: [],
    schemaPath: "lib/apps/timesheets/schema.sql",
    migrationNamespace: "timesheets",
    navigation: [
      {
        key: "timesheets.root",
        label: "Timesheets",
        href: "/apps/timesheets",
        iconKey: "clock",
        parentKey: null,
        actionKey: "timesheets.open",
        order: 10,
      },
    ],
    actions: [
      {
        key: "timesheets.open",
        name: "Open Timesheets",
        type: 'route',
        href: "/apps/timesheets",
        viewKeys: ["timesheets.workspace"],
        target: 'current',
      },
    ],
    views: [
      {
        key: "timesheets.workspace",
        name: "Timesheets workspace",
        type: 'workspace',
        route: "/apps/timesheets",
        priority: 10,
      },
    ],
    resources: [],
    security: {
      permissions: [],
      recordPolicies: [],
      fieldPolicies: [],
    },
    settings: [],
    extensions: {
      dashboard: false,
      search: false,
      notifications: false,
      activity: false,
      automationTriggers: false,
      automationActions: false,
      aiTools: false,
      integrationProviders: false,
      apiEndpoints: false,
      dataExport: false,
      dataErasure: false,
    },
  }),

  defineSamiModule({
    key: "field_services",
    name: "Field Services",
    version: '1.0.0',
    description: "Manage work performed at customer locations.",
    category: "work",
    icon: "map-pin",
    route: "apps/field_services",
    application: true,
    installable: true,
    autoInstall: false,
    recommended: false,
    depends: [],
    optionalDepends: [],
    schemaPath: "lib/apps/field_services/schema.sql",
    migrationNamespace: "field_services",
    navigation: [
      {
        key: "field_services.root",
        label: "Field Services",
        href: "/apps/field_services",
        iconKey: "map-pin",
        parentKey: null,
        actionKey: "field_services.open",
        order: 10,
      },
    ],
    actions: [
      {
        key: "field_services.open",
        name: "Open Field Services",
        type: 'route',
        href: "/apps/field_services",
        viewKeys: ["field_services.workspace"],
        target: 'current',
      },
    ],
    views: [
      {
        key: "field_services.workspace",
        name: "Field Services workspace",
        type: 'workspace',
        route: "/apps/field_services",
        priority: 10,
      },
    ],
    resources: [],
    security: {
      permissions: [],
      recordPolicies: [],
      fieldPolicies: [],
    },
    settings: [],
    extensions: {
      dashboard: false,
      search: false,
      notifications: false,
      activity: false,
      automationTriggers: false,
      automationActions: false,
      aiTools: false,
      integrationProviders: false,
      apiEndpoints: false,
      dataExport: false,
      dataErasure: false,
    },
  }),

  defineSamiModule({
    key: "helpdesk",
    name: "Helpdesk",
    version: '1.0.0',
    description: "Manage customer support tickets and service requests.",
    category: "work",
    icon: "headphones",
    route: "apps/helpdesk",
    application: true,
    installable: true,
    autoInstall: false,
    recommended: false,
    depends: [],
    optionalDepends: [],
    schemaPath: "lib/apps/helpdesk/schema.sql",
    migrationNamespace: "helpdesk",
    navigation: [
      {
        key: "helpdesk.root",
        label: "Helpdesk",
        href: "/apps/helpdesk",
        iconKey: "headphones",
        parentKey: null,
        actionKey: "helpdesk.open",
        order: 10,
      },
    ],
    actions: [
      {
        key: "helpdesk.open",
        name: "Open Helpdesk",
        type: 'route',
        href: "/apps/helpdesk",
        viewKeys: ["helpdesk.workspace"],
        target: 'current',
      },
    ],
    views: [
      {
        key: "helpdesk.workspace",
        name: "Helpdesk workspace",
        type: 'workspace',
        route: "/apps/helpdesk",
        priority: 10,
      },
    ],
    resources: [],
    security: {
      permissions: [],
      recordPolicies: [],
      fieldPolicies: [],
    },
    settings: [],
    extensions: {
      dashboard: false,
      search: false,
      notifications: false,
      activity: false,
      automationTriggers: false,
      automationActions: false,
      aiTools: false,
      integrationProviders: false,
      apiEndpoints: false,
      dataExport: false,
      dataErasure: false,
    },
  }),

  defineSamiModule({
    key: "planning",
    name: "Planning",
    version: '1.0.0',
    description: "Plan schedules, shifts and assignments.",
    category: "work",
    icon: "calendar-clock",
    route: "apps/planning",
    application: true,
    installable: true,
    autoInstall: false,
    recommended: false,
    depends: [],
    optionalDepends: [],
    schemaPath: "lib/apps/planning/schema.sql",
    migrationNamespace: "planning",
    navigation: [
      {
        key: "planning.root",
        label: "Planning",
        href: "/apps/planning",
        iconKey: "calendar-clock",
        parentKey: null,
        actionKey: "planning.open",
        order: 10,
      },
    ],
    actions: [
      {
        key: "planning.open",
        name: "Open Planning",
        type: 'route',
        href: "/apps/planning",
        viewKeys: ["planning.workspace"],
        target: 'current',
      },
    ],
    views: [
      {
        key: "planning.workspace",
        name: "Planning workspace",
        type: 'workspace',
        route: "/apps/planning",
        priority: 10,
      },
    ],
    resources: [],
    security: {
      permissions: [],
      recordPolicies: [],
      fieldPolicies: [],
    },
    settings: [],
    extensions: {
      dashboard: false,
      search: false,
      notifications: false,
      activity: false,
      automationTriggers: false,
      automationActions: false,
      aiTools: false,
      integrationProviders: false,
      apiEndpoints: false,
      dataExport: false,
      dataErasure: false,
    },
  }),

  defineSamiModule({
    key: "appointments",
    name: "Appointments",
    version: '1.0.0',
    description: "Let customers book appointments and manage schedules.",
    category: "work",
    icon: "calendar",
    route: "apps/appointments",
    application: true,
    installable: true,
    autoInstall: false,
    recommended: false,
    depends: [],
    optionalDepends: [],
    schemaPath: "lib/apps/appointments/schema.sql",
    migrationNamespace: "appointments",
    navigation: [
      {
        key: "appointments.root",
        label: "Appointments",
        href: "/apps/appointments",
        iconKey: "calendar",
        parentKey: null,
        actionKey: "appointments.open",
        order: 10,
      },
    ],
    actions: [
      {
        key: "appointments.open",
        name: "Open Appointments",
        type: 'route',
        href: "/apps/appointments",
        viewKeys: ["appointments.workspace"],
        target: 'current',
      },
    ],
    views: [
      {
        key: "appointments.workspace",
        name: "Appointments workspace",
        type: 'workspace',
        route: "/apps/appointments",
        priority: 10,
      },
    ],
    resources: [],
    security: {
      permissions: [],
      recordPolicies: [],
      fieldPolicies: [],
    },
    settings: [],
    extensions: {
      dashboard: false,
      search: false,
      notifications: false,
      activity: false,
      automationTriggers: false,
      automationActions: false,
      aiTools: false,
      integrationProviders: false,
      apiEndpoints: false,
      dataExport: false,
      dataErasure: false,
    },
  }),

  ...ADDITIONAL_FIRST_PARTY_SAMI_MODULES,
];

export const FIRST_PARTY_SAMI_MODULES:
  SamiModuleManifest[] =
  BASE_FIRST_PARTY_SAMI_MODULES.map(
    withEnterpriseModuleDefaults,
  );
