"use client";
import { useState,type FormEvent } from 'react';
import { Calculator,Plus,ShieldCheck } from 'lucide-react';
import { useRouter } from 'next/navigation';
import SaMiOverlay from '@/app/components/SaMiOverlay';
import { useSaMiOverlay } from '@/app/components/useSaMiOverlay';
import type { AccountingTaxesWorkspace } from '@/lib/apps/accounting/taxes';
import { formatAccountingAmount } from '@/lib/apps/accounting/validation';
import styles from './AccountingFoundation.module.css';

export default function AccountingTaxes({data,canCreate,canEdit}:{data:AccountingTaxesWorkspace;canCreate:boolean;canEdit:boolean}){
 const router=useRouter(),{overlay,showSuccess,showError,closeOverlay}=useSaMiOverlay();const[busy,setBusy]=useState(''),[showCode,setShowCode]=useState(false),[showGroup,setShowGroup]=useState(false);
 const[draft,setDraft]=useState({code:'',name:'',scope:'sale',behavior:'add',computation:'percent',rate:'0',fixedAmount:'0',priceIncluded:false,includeBaseAmount:false,recoverablePercent:'0',taxAccountId:'',recoverableAccountId:'',jurisdictionCode:'',reportingCode:'',effectiveFrom:'',effectiveTo:'',sequence:'100'});
 const[group,setGroup]=useState({code:'',name:'',scope:'sale',taxCodeIds:[] as string[]});const[preview,setPreview]=useState({amount:'1000',date:new Date().toISOString().slice(0,10),taxCodeIds:[] as string[]});const[result,setResult]=useState<null|{untaxedAmount:string;taxTotal:string;withholdingTotal:string;totalAmount:string}>(null);
 const amount=(v:string)=>formatAccountingAmount(v,data.currency),active=data.codes.filter(r=>r.status==='active');
 async function request(body:Record<string,unknown>){const response=await fetch('/api/apps/accounting/taxes',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)}),payload=await response.json();if(!response.ok)throw new Error(payload.error||'Tax action failed.');return payload.result;}
 async function createCode(e:FormEvent){e.preventDefault();if(!canCreate)return;setBusy('code');try{await request({action:'create-code',expectedCompanyId:data.companyId,...draft});showSuccess('Tax code created','The tax is now available to Accounting workflows.');setShowCode(false);router.refresh();}catch(error){showError('Tax code could not be created',error instanceof Error?error.message:'Retry this tax code.');}finally{setBusy('');}}
 async function createGroup(e:FormEvent){e.preventDefault();if(!canCreate)return;setBusy('group');try{await request({action:'create-group',expectedCompanyId:data.companyId,...group});showSuccess('Tax group created','The ordered tax group is ready.');setShowGroup(false);router.refresh();}catch(error){showError('Tax group could not be created',error instanceof Error?error.message:'Retry this group.');}finally{setBusy('');}}
 async function toggle(id:string,status:string){if(!canEdit)return;setBusy(id);try{await request({action:'set-status',taxCodeId:id,status:status==='active'?'archived':'active'});router.refresh();}catch(error){showError('Tax status could not be changed',error instanceof Error?error.message:'Retry.');}finally{setBusy('');}}
 async function calc(e:FormEvent){e.preventDefault();setBusy('preview');try{setResult(await request({action:'preview',...preview}));}catch(error){showError('Tax preview failed',error instanceof Error?error.message:'Check selected taxes.');}finally{setBusy('');}}
 return <div className={styles.workspace}>
  <div className={styles.heading}><div><div className={styles.eyebrow}>Accounting · Tax engine · {data.currency}</div><h2>Taxes</h2><p>Configure effective-dated sales, purchase and withholding taxes with inclusive pricing, compounding, recovery and ledger mappings.</p></div><div className={styles.actions}>{canCreate?<button className={styles.button} type="button" onClick={()=>setShowGroup(v=>!v)}><Plus size={15}/> New group</button>:null}{canCreate?<button className={styles.primary} type="button" onClick={()=>setShowCode(v=>!v)}><Plus size={15}/> New tax code</button>:null}</div></div>
  <section className={styles.financeCards}><div className={styles.financeCard}><span>Active tax codes</span><strong>{data.metrics.activeCodes}</strong><small>Company definitions</small></div><div className={styles.financeCard}><span>Active groups</span><strong>{data.metrics.groups}</strong><small>Ordered calculations</small></div><div className={styles.financeCard}><span>Tax register</span><strong>{data.metrics.registerEntries}</strong><small>Latest posted sources</small></div><div className={styles.financeCard}><span>Localization</span><strong>Core ready</strong><small>Jurisdiction rules remain configuration-owned</small></div></section>
  <div className={styles.notice}><ShieldCheck size={16}/> The tax core is jurisdiction-neutral. Kenya statutory defaults and shared eTIMS mapping are added in Accounting Part 15 instead of hardcoding rates here.</div>
  {showCode?<form className={styles.panel} onSubmit={createCode}><div className={styles.panelHeading}><div><span className={styles.eyebrow}>Tax authority</span><h3>Create tax code</h3></div></div><div className={styles.setupGrid}>
   <label>Code<input required value={draft.code} onChange={e=>setDraft({...draft,code:e.target.value})}/></label><label>Name<input required value={draft.name} onChange={e=>setDraft({...draft,name:e.target.value})}/></label>
   <label>Scope<select value={draft.scope} onChange={e=>setDraft({...draft,scope:e.target.value,recoverablePercent:e.target.value==='purchase'||e.target.value==='both'?'100':'0'})}><option value="sale">Sales</option><option value="purchase">Purchase</option><option value="both">Both</option><option value="withholding">Withholding</option></select></label>
   <label>Behavior<select value={draft.behavior} onChange={e=>setDraft({...draft,behavior:e.target.value})}><option value="add">Add to total</option><option value="withhold">Withhold</option></select></label>
   <label>Calculation<select value={draft.computation} onChange={e=>setDraft({...draft,computation:e.target.value})}><option value="percent">Percentage</option><option value="fixed">Fixed amount</option></select></label>
   {draft.computation==='percent'?<label>Rate %<input required value={draft.rate} onChange={e=>setDraft({...draft,rate:e.target.value})}/></label>:<label>Fixed amount<input required value={draft.fixedAmount} onChange={e=>setDraft({...draft,fixedAmount:e.target.value})}/></label>}
   <label>Recoverable %<input required value={draft.recoverablePercent} onChange={e=>setDraft({...draft,recoverablePercent:e.target.value})}/></label>
   <label>Tax / liability account<select value={draft.taxAccountId} onChange={e=>setDraft({...draft,taxAccountId:e.target.value})}><option value="">Not mapped</option>{data.accounts.map(a=><option key={a.id} value={a.id}>{a.code} · {a.name}</option>)}</select></label>
   <label>Recoverable input-tax account<select value={draft.recoverableAccountId} onChange={e=>setDraft({...draft,recoverableAccountId:e.target.value})}><option value="">Not mapped</option>{data.accounts.map(a=><option key={a.id} value={a.id}>{a.code} · {a.name}</option>)}</select></label>
   <label>Jurisdiction code<input value={draft.jurisdictionCode} onChange={e=>setDraft({...draft,jurisdictionCode:e.target.value})}/></label><label>Reporting code<input value={draft.reportingCode} onChange={e=>setDraft({...draft,reportingCode:e.target.value})}/></label>
   <label>Effective from<input type="date" value={draft.effectiveFrom} onChange={e=>setDraft({...draft,effectiveFrom:e.target.value})}/></label><label>Effective to<input type="date" value={draft.effectiveTo} onChange={e=>setDraft({...draft,effectiveTo:e.target.value})}/></label>
   <label>Sequence<input type="number" min="0" value={draft.sequence} onChange={e=>setDraft({...draft,sequence:e.target.value})}/></label>
   <label><input type="checkbox" checked={draft.priceIncluded} onChange={e=>setDraft({...draft,priceIncluded:e.target.checked})}/> Price included</label><label><input type="checkbox" checked={draft.includeBaseAmount} onChange={e=>setDraft({...draft,includeBaseAmount:e.target.checked})}/> Affect later tax base</label>
  </div><div className={styles.actions}><button type="button" className={styles.button} onClick={()=>setShowCode(false)}>Cancel</button><button disabled={busy==='code'} className={styles.primary}>Save tax code</button></div></form>:null}
  {showGroup?<form className={styles.panel} onSubmit={createGroup}><div className={styles.panelHeading}><div><span className={styles.eyebrow}>Multi-tax</span><h3>Create tax group</h3></div></div><div className={styles.setupGrid}><label>Code<input required value={group.code} onChange={e=>setGroup({...group,code:e.target.value})}/></label><label>Name<input required value={group.name} onChange={e=>setGroup({...group,name:e.target.value})}/></label><label>Scope<select value={group.scope} onChange={e=>setGroup({...group,scope:e.target.value})}><option value="sale">Sales</option><option value="purchase">Purchase</option><option value="both">Both</option><option value="withholding">Withholding</option></select></label></div><div className={styles.setupGrid}>{active.map(r=><label key={r.id}><input type="checkbox" checked={group.taxCodeIds.includes(r.id)} onChange={e=>setGroup({...group,taxCodeIds:e.target.checked?[...group.taxCodeIds,r.id]:group.taxCodeIds.filter(id=>id!==r.id)})}/>{r.code} · {r.name}</label>)}</div><div className={styles.actions}><button type="button" className={styles.button} onClick={()=>setShowGroup(false)}>Cancel</button><button className={styles.primary}>Save group</button></div></form>:null}
  <section className={styles.panel}><div className={styles.panelHeading}><div><span className={styles.eyebrow}>Tax definitions</span><h3>Company tax codes</h3></div></div><div className={styles.tableWrap}><table><thead><tr><th>Tax</th><th>Scope</th><th>Calculation</th><th>Pricing</th><th>Recovery</th><th>Status</th><th></th></tr></thead><tbody>{data.codes.map(r=><tr key={r.id}><td><strong>{r.code} · {r.name}</strong><span className={styles.meta}>{r.jurisdiction_code||'General'}{r.reporting_code?' · '+r.reporting_code:''}</span></td><td>{r.scope} · {r.behavior}</td><td>{r.computation==='percent'?r.rate+'%':amount(r.fixed_amount)}</td><td>{r.price_included?'Included':'Exclusive'}{r.include_base_amount?' · compound':''}</td><td>{r.recoverable_percent}%</td><td><span className={styles.badge}>{r.status}</span></td><td>{canEdit?<button type="button" className={styles.button} disabled={busy===r.id} onClick={()=>toggle(r.id,r.status)}>{r.status==='active'?'Archive':'Restore'}</button>:null}</td></tr>)}</tbody></table></div></section>
  <section className={styles.panel}><div className={styles.panelHeading}><div><span className={styles.eyebrow}>Calculation proof</span><h3>Preview tax result</h3></div><Calculator size={20}/></div><form onSubmit={calc}><div className={styles.setupGrid}><label>Amount<input required value={preview.amount} onChange={e=>setPreview({...preview,amount:e.target.value})}/></label><label>Date<input required type="date" value={preview.date} onChange={e=>setPreview({...preview,date:e.target.value})}/></label></div><div className={styles.setupGrid}>{active.map(r=><label key={r.id}><input type="checkbox" checked={preview.taxCodeIds.includes(r.id)} onChange={e=>setPreview({...preview,taxCodeIds:e.target.checked?[...preview.taxCodeIds,r.id]:preview.taxCodeIds.filter(id=>id!==r.id)})}/>{r.code} · {r.name}</label>)}</div><div className={styles.actions}><button className={styles.primary}>Calculate</button></div></form>{result?<div className={styles.receivableControlValues}><div><span>Untaxed</span><strong>{amount(result.untaxedAmount)}</strong></div><div><span>Tax</span><strong>{amount(result.taxTotal)}</strong></div><div><span>Withholding</span><strong>{amount(result.withholdingTotal)}</strong></div><div><span>Total</span><strong>{amount(result.totalAmount)}</strong></div></div>:null}</section>
  <section className={styles.panel}><div className={styles.panelHeading}><div><span className={styles.eyebrow}>Tax register</span><h3>Latest source entries</h3></div></div>{data.register.length?<div className={styles.tableWrap}><table><thead><tr><th>Date</th><th>Tax</th><th>Source</th><th>Taxable</th><th>Tax</th><th>Recoverable</th><th>Authority</th></tr></thead><tbody>{data.register.map(r=><tr key={r.id}><td>{r.transaction_date}</td><td>{r.code} · {r.name}</td><td>{r.source_module} · {r.source_type}</td><td>{amount(r.taxable_amount)}</td><td>{r.entry_effect===-1?'-':''}{amount(r.tax_amount)}</td><td>{r.entry_effect===-1?'-':''}{amount(r.recoverable_amount)}</td><td>{r.authority?String(r.authority)+(r.authority_reference?' · '+String(r.authority_reference):''):'—'}</td></tr>)}</tbody></table></div>:<p className={styles.meta}>No posted source has recorded tax-register entries yet.</p>}</section>
  <SaMiOverlay {...overlay} onClose={closeOverlay}/>
 </div>;
}
