-- ============================================================
-- SaMi Control DB Migration
-- Category 22: Expand first-party business app registry to 80
-- ============================================================
--
-- The original 36 business module foundations and these additional
-- 44 are one canonical SaMi app catalog. This migration registers
-- the additional keys in the same control.modules table used by
-- onboarding, app lifecycle, permissions and workspace context.
--
-- Module business data remains inside tenant databases.
-- No tenant schema is created here.
-- ============================================================

INSERT INTO modules (
  key,
  name,
  version,
  description,
  category,
  icon,
  is_core,
  is_ai_module,
  dependencies,
  status,
  manifest,
  capabilities,
  ai_discovery_enabled,
  created_at,
  updated_at,
  deleted_at
)
VALUES
  (
    'billing',
    'Billing',
    '1.0.0',
    'Manage customer billing cycles, recurring charges and revenue schedules.',
    'finance',
    'repeat',
    FALSE,
    FALSE,
    '["invoicing"]'::jsonb,
    'active',
    '{}'::jsonb,
    '[]'::jsonb,
    TRUE,
    NOW(),
    NOW(),
    NULL
  ),
  (
    'payments',
    'Payments',
    '1.0.0',
    'Collect, reconcile and track business payments across supported channels.',
    'finance',
    'receipt',
    FALSE,
    FALSE,
    '["accounting"]'::jsonb,
    'active',
    '{}'::jsonb,
    '[]'::jsonb,
    TRUE,
    NOW(),
    NOW(),
    NULL
  ),
  (
    'budgeting',
    'Budgeting',
    '1.0.0',
    'Plan budgets, compare actuals and manage departmental spending targets.',
    'finance',
    'bar-chart',
    FALSE,
    FALSE,
    '["accounting"]'::jsonb,
    'active',
    '{}'::jsonb,
    '[]'::jsonb,
    TRUE,
    NOW(),
    NOW(),
    NULL
  ),
  (
    'cash_flow',
    'Cash Flow',
    '1.0.0',
    'Forecast cash positions, inflows, outflows and liquidity requirements.',
    'finance',
    'bar-chart',
    FALSE,
    FALSE,
    '["accounting"]'::jsonb,
    'active',
    '{}'::jsonb,
    '[]'::jsonb,
    TRUE,
    NOW(),
    NOW(),
    NULL
  ),
  (
    'fixed_assets',
    'Fixed Assets',
    '1.0.0',
    'Track capitalization, depreciation, transfers and disposal of fixed assets.',
    'finance',
    'calculator',
    FALSE,
    FALSE,
    '["accounting"]'::jsonb,
    'active',
    '{}'::jsonb,
    '[]'::jsonb,
    TRUE,
    NOW(),
    NOW(),
    NULL
  ),
  (
    'tax',
    'Tax',
    '1.0.0',
    'Manage tax registrations, filings, obligations and compliance workflows.',
    'finance',
    'file-text',
    FALSE,
    FALSE,
    '["accounting"]'::jsonb,
    'active',
    '{}'::jsonb,
    '[]'::jsonb,
    TRUE,
    NOW(),
    NOW(),
    NULL
  ),
  (
    'bookings',
    'Bookings',
    '1.0.0',
    'Accept customer bookings for services, resources, locations and staff.',
    'sales',
    'calendar',
    FALSE,
    FALSE,
    '["appointments"]'::jsonb,
    'active',
    '{}'::jsonb,
    '[]'::jsonb,
    TRUE,
    NOW(),
    NOW(),
    NULL
  ),
  (
    'customer_portal',
    'Customer Portal',
    '1.0.0',
    'Give customers secure self-service access to documents, orders and requests.',
    'sales',
    'users',
    FALSE,
    FALSE,
    '[]'::jsonb,
    'active',
    '{}'::jsonb,
    '[]'::jsonb,
    TRUE,
    NOW(),
    NOW(),
    NULL
  ),
  (
    'sales_inbox',
    'Sales Inbox',
    '1.0.0',
    'Unify sales conversations, customer replies and deal-related communication.',
    'sales',
    'mail',
    FALSE,
    FALSE,
    '["crm"]'::jsonb,
    'active',
    '{}'::jsonb,
    '[]'::jsonb,
    TRUE,
    NOW(),
    NOW(),
    NULL
  ),
  (
    'cpq',
    'CPQ',
    '1.0.0',
    'Configure complex offers, calculate prices and generate governed quotations.',
    'sales',
    'calculator',
    FALSE,
    FALSE,
    '["sales"]'::jsonb,
    'active',
    '{}'::jsonb,
    '[]'::jsonb,
    TRUE,
    NOW(),
    NOW(),
    NULL
  ),
  (
    'commissions',
    'Sales Commissions',
    '1.0.0',
    'Define commission rules and track earned sales incentives.',
    'sales',
    'users',
    FALSE,
    FALSE,
    '["sales"]'::jsonb,
    'active',
    '{}'::jsonb,
    '[]'::jsonb,
    TRUE,
    NOW(),
    NOW(),
    NULL
  ),
  (
    'ecommerce',
    'E-commerce',
    '1.0.0',
    'Run an online storefront connected to products, customers and fulfillment.',
    'commerce',
    'shopping-bag',
    FALSE,
    FALSE,
    '["sales","inventory"]'::jsonb,
    'active',
    '{}'::jsonb,
    '[]'::jsonb,
    TRUE,
    NOW(),
    NOW(),
    NULL
  ),
  (
    'checkout',
    'Checkout',
    '1.0.0',
    'Create hosted checkout experiences for products, services and payment links.',
    'commerce',
    'shopping-cart',
    FALSE,
    FALSE,
    '["payments"]'::jsonb,
    'active',
    '{}'::jsonb,
    '[]'::jsonb,
    TRUE,
    NOW(),
    NOW(),
    NULL
  ),
  (
    'loyalty',
    'Loyalty',
    '1.0.0',
    'Manage customer points, rewards, tiers and retention programs.',
    'commerce',
    'users',
    FALSE,
    FALSE,
    '[]'::jsonb,
    'active',
    '{}'::jsonb,
    '[]'::jsonb,
    TRUE,
    NOW(),
    NOW(),
    NULL
  ),
  (
    'gift_cards',
    'Gift Cards',
    '1.0.0',
    'Issue, redeem and reconcile digital and physical gift-card balances.',
    'commerce',
    'shopping-bag',
    FALSE,
    FALSE,
    '["payments"]'::jsonb,
    'active',
    '{}'::jsonb,
    '[]'::jsonb,
    TRUE,
    NOW(),
    NOW(),
    NULL
  ),
  (
    'marketplace',
    'Marketplace',
    '1.0.0',
    'Coordinate multi-seller catalogs, orders, commissions and settlements.',
    'commerce',
    'store',
    FALSE,
    FALSE,
    '["ecommerce","payments"]'::jsonb,
    'active',
    '{}'::jsonb,
    '[]'::jsonb,
    TRUE,
    NOW(),
    NOW(),
    NULL
  ),
  (
    'warehouse',
    'Warehouse',
    '1.0.0',
    'Coordinate warehouse locations, put-away, picking and internal stock flows.',
    'supply_chain',
    'boxes',
    FALSE,
    FALSE,
    '["inventory"]'::jsonb,
    'active',
    '{}'::jsonb,
    '[]'::jsonb,
    TRUE,
    NOW(),
    NOW(),
    NULL
  ),
  (
    'shipping',
    'Shipping',
    '1.0.0',
    'Prepare shipments, carrier handoffs, tracking and delivery exceptions.',
    'supply_chain',
    'package',
    FALSE,
    FALSE,
    '["inventory"]'::jsonb,
    'active',
    '{}'::jsonb,
    '[]'::jsonb,
    TRUE,
    NOW(),
    NOW(),
    NULL
  ),
  (
    'demand_planning',
    'Demand Planning',
    '1.0.0',
    'Forecast product demand and translate forecasts into replenishment signals.',
    'supply_chain',
    'bar-chart',
    FALSE,
    FALSE,
    '["inventory"]'::jsonb,
    'active',
    '{}'::jsonb,
    '[]'::jsonb,
    TRUE,
    NOW(),
    NOW(),
    NULL
  ),
  (
    'vendor_portal',
    'Vendor Portal',
    '1.0.0',
    'Give suppliers controlled access to purchase orders, deliveries and documents.',
    'supply_chain',
    'users',
    FALSE,
    FALSE,
    '["purchase"]'::jsonb,
    'active',
    '{}'::jsonb,
    '[]'::jsonb,
    TRUE,
    NOW(),
    NOW(),
    NULL
  ),
  (
    'barcode',
    'Barcode',
    '1.0.0',
    'Use barcode workflows for receiving, picking, inventory and fulfillment.',
    'supply_chain',
    'package',
    FALSE,
    FALSE,
    '["inventory"]'::jsonb,
    'active',
    '{}'::jsonb,
    '[]'::jsonb,
    TRUE,
    NOW(),
    NOW(),
    NULL
  ),
  (
    'facilities',
    'Facilities',
    '1.0.0',
    'Manage sites, rooms, utilities, service requests and facility operations.',
    'operations',
    'home',
    FALSE,
    FALSE,
    '[]'::jsonb,
    'active',
    '{}'::jsonb,
    '[]'::jsonb,
    TRUE,
    NOW(),
    NOW(),
    NULL
  ),
  (
    'assets',
    'Operational Assets',
    '1.0.0',
    'Track operational equipment, ownership, assignment and lifecycle status.',
    'operations',
    'wrench',
    FALSE,
    FALSE,
    '[]'::jsonb,
    'active',
    '{}'::jsonb,
    '[]'::jsonb,
    TRUE,
    NOW(),
    NOW(),
    NULL
  ),
  (
    'work_orders',
    'Work Orders',
    '1.0.0',
    'Create, assign and monitor operational jobs from request through completion.',
    'operations',
    'clipboard-list',
    FALSE,
    FALSE,
    '[]'::jsonb,
    'active',
    '{}'::jsonb,
    '[]'::jsonb,
    TRUE,
    NOW(),
    NOW(),
    NULL
  ),
  (
    'inspections',
    'Inspections',
    '1.0.0',
    'Run structured inspections, checklists, findings and corrective actions.',
    'operations',
    'clipboard-check',
    FALSE,
    FALSE,
    '[]'::jsonb,
    'active',
    '{}'::jsonb,
    '[]'::jsonb,
    TRUE,
    NOW(),
    NOW(),
    NULL
  ),
  (
    'safety',
    'Safety',
    '1.0.0',
    'Manage incidents, safety actions, compliance checks and operational risk.',
    'operations',
    'shield-check',
    FALSE,
    FALSE,
    '[]'::jsonb,
    'active',
    '{}'::jsonb,
    '[]'::jsonb,
    TRUE,
    NOW(),
    NOW(),
    NULL
  ),
  (
    'payroll',
    'Payroll',
    '1.0.0',
    'Calculate payroll, deductions, benefits and employee pay runs.',
    'people',
    'calculator',
    FALSE,
    FALSE,
    '["employees"]'::jsonb,
    'active',
    '{}'::jsonb,
    '[]'::jsonb,
    TRUE,
    NOW(),
    NOW(),
    NULL
  ),
  (
    'attendance',
    'Attendance',
    '1.0.0',
    'Track attendance, clock events, lateness and attendance policies.',
    'people',
    'clock',
    FALSE,
    FALSE,
    '["employees"]'::jsonb,
    'active',
    '{}'::jsonb,
    '[]'::jsonb,
    TRUE,
    NOW(),
    NOW(),
    NULL
  ),
  (
    'shifts',
    'Shifts',
    '1.0.0',
    'Build staff rosters, shift rotations and coverage schedules.',
    'people',
    'calendar-clock',
    FALSE,
    FALSE,
    '["employees"]'::jsonb,
    'active',
    '{}'::jsonb,
    '[]'::jsonb,
    TRUE,
    NOW(),
    NOW(),
    NULL
  ),
  (
    'onboarding',
    'Employee Onboarding',
    '1.0.0',
    'Coordinate new-hire tasks, documents, access and induction journeys.',
    'people',
    'user-plus',
    FALSE,
    FALSE,
    '["employees"]'::jsonb,
    'active',
    '{}'::jsonb,
    '[]'::jsonb,
    TRUE,
    NOW(),
    NOW(),
    NULL
  ),
  (
    'learning',
    'Learning',
    '1.0.0',
    'Create internal courses, learning paths, assessments and training records.',
    'people',
    'file-text',
    FALSE,
    FALSE,
    '["employees"]'::jsonb,
    'active',
    '{}'::jsonb,
    '[]'::jsonb,
    TRUE,
    NOW(),
    NOW(),
    NULL
  ),
  (
    'benefits',
    'Benefits',
    '1.0.0',
    'Manage employee benefit programs, eligibility and enrollment records.',
    'people',
    'users',
    FALSE,
    FALSE,
    '["employees"]'::jsonb,
    'active',
    '{}'::jsonb,
    '[]'::jsonb,
    TRUE,
    NOW(),
    NOW(),
    NULL
  ),
  (
    'org_chart',
    'Organization Chart',
    '1.0.0',
    'Visualize reporting lines, teams, roles and organizational structure.',
    'people',
    'users',
    FALSE,
    FALSE,
    '["employees"]'::jsonb,
    'active',
    '{}'::jsonb,
    '[]'::jsonb,
    TRUE,
    NOW(),
    NOW(),
    NULL
  ),
  (
    'landing_pages',
    'Landing Pages',
    '1.0.0',
    'Build campaign landing pages connected to leads, forms and analytics.',
    'marketing',
    'app-window',
    FALSE,
    FALSE,
    '[]'::jsonb,
    'active',
    '{}'::jsonb,
    '[]'::jsonb,
    TRUE,
    NOW(),
    NOW(),
    NULL
  ),
  (
    'web_analytics',
    'Web Analytics',
    '1.0.0',
    'Measure website acquisition, behavior, conversion and campaign performance.',
    'marketing',
    'bar-chart',
    FALSE,
    FALSE,
    '[]'::jsonb,
    'active',
    '{}'::jsonb,
    '[]'::jsonb,
    TRUE,
    NOW(),
    NOW(),
    NULL
  ),
  (
    'ads',
    'Ads',
    '1.0.0',
    'Coordinate paid campaigns, audiences, spend and performance reporting.',
    'marketing',
    'megaphone',
    FALSE,
    FALSE,
    '[]'::jsonb,
    'active',
    '{}'::jsonb,
    '[]'::jsonb,
    TRUE,
    NOW(),
    NOW(),
    NULL
  ),
  (
    'seo',
    'SEO',
    '1.0.0',
    'Track search visibility, content opportunities and organic performance.',
    'marketing',
    'bar-chart',
    FALSE,
    FALSE,
    '[]'::jsonb,
    'active',
    '{}'::jsonb,
    '[]'::jsonb,
    TRUE,
    NOW(),
    NOW(),
    NULL
  ),
  (
    'lead_capture',
    'Lead Capture',
    '1.0.0',
    'Capture and route inbound leads from forms, campaigns and digital channels.',
    'marketing',
    'user-plus',
    FALSE,
    FALSE,
    '["crm"]'::jsonb,
    'active',
    '{}'::jsonb,
    '[]'::jsonb,
    TRUE,
    NOW(),
    NOW(),
    NULL
  ),
  (
    'mail',
    'Mail',
    '1.0.0',
    'Business email connected to SaMi contacts, activities and AI assistance.',
    'work',
    'mail',
    FALSE,
    FALSE,
    '[]'::jsonb,
    'active',
    '{}'::jsonb,
    '[]'::jsonb,
    TRUE,
    NOW(),
    NOW(),
    NULL
  ),
  (
    'chat',
    'Team Chat',
    '1.0.0',
    'Real-time team messaging with workspace-aware channels and conversations.',
    'work',
    'message-square',
    FALSE,
    FALSE,
    '[]'::jsonb,
    'active',
    '{}'::jsonb,
    '[]'::jsonb,
    TRUE,
    NOW(),
    NOW(),
    NULL
  ),
  (
    'meetings',
    'Meetings',
    '1.0.0',
    'Plan and run online meetings linked to customers, projects and teams.',
    'work',
    'users',
    FALSE,
    FALSE,
    '[]'::jsonb,
    'active',
    '{}'::jsonb,
    '[]'::jsonb,
    TRUE,
    NOW(),
    NOW(),
    NULL
  ),
  (
    'calendar',
    'Calendar',
    '1.0.0',
    'Coordinate personal, team and business calendars across SaMi apps.',
    'work',
    'calendar',
    FALSE,
    FALSE,
    '[]'::jsonb,
    'active',
    '{}'::jsonb,
    '[]'::jsonb,
    TRUE,
    NOW(),
    NOW(),
    NULL
  ),
  (
    'team_inbox',
    'Team Inbox',
    '1.0.0',
    'Manage shared business inboxes with assignment, ownership and collaboration.',
    'work',
    'mail',
    FALSE,
    FALSE,
    '[]'::jsonb,
    'active',
    '{}'::jsonb,
    '[]'::jsonb,
    TRUE,
    NOW(),
    NOW(),
    NULL
  ),
  (
    'whiteboard',
    'Whiteboard',
    '1.0.0',
    'Collaborate visually on plans, workflows, ideas and business processes.',
    'work',
    'pen-tool',
    FALSE,
    FALSE,
    '[]'::jsonb,
    'active',
    '{}'::jsonb,
    '[]'::jsonb,
    TRUE,
    NOW(),
    NOW(),
    NULL
  )
ON CONFLICT (key)
DO UPDATE SET
  name =
    EXCLUDED.name,
  version =
    EXCLUDED.version,
  description =
    EXCLUDED.description,
  category =
    EXCLUDED.category,
  icon =
    EXCLUDED.icon,
  is_core =
    FALSE,
  is_ai_module =
    FALSE,
  dependencies =
    EXCLUDED.dependencies,
  status =
    'active',
  ai_discovery_enabled =
    TRUE,
  deleted_at =
    NULL,
  updated_at =
    NOW();
