import crypto from 'crypto';

import {
  queryControl,
} from '@/lib/db/control';

/* ============================================================
   CONSTANTS
   ============================================================ */

const DEFAULT_RECOVERY_CODE_COUNT =
  10;

const MAX_RECOVERY_CODE_COUNT =
  20;

/*
 * 6 random bytes = 48 random bits.
 *
 * Encoded as 12 hexadecimal characters:
 *
 * XXXX-XXXX-XXXX
 *
 * Keep this format stable because the SaMi UI may already
 * display recovery codes using this structure.
 */
const RECOVERY_CODE_BYTES =
  6;

const RECOVERY_CODE_NORMALIZED_LENGTH =
  RECOVERY_CODE_BYTES * 2;

const MIN_PEPPER_LENGTH =
  32;

/* ============================================================
   CONFIGURATION
   ============================================================ */

/**
 * Recovery codes use their own dedicated pepper.
 *
 * Do NOT silently fall back to:
 *
 * - SESSION_SECRET
 * - AUTH_ENCRYPTION_KEY
 * - NEXTAUTH_SECRET
 * - database passwords
 *
 * Authentication secrets should have separate purposes.
 */
function getRecoveryCodePepper():
  string {
  const pepper =
    process.env
      .AUTH_RECOVERY_CODE_PEPPER
      ?.trim();

  if (!pepper) {
    throw new Error(
      'AUTH_RECOVERY_CODE_PEPPER is missing.'
    );
  }

  if (
    pepper.length <
    MIN_PEPPER_LENGTH
  ) {
    throw new Error(
      'AUTH_RECOVERY_CODE_PEPPER must contain at least 32 characters.'
    );
  }

  return pepper;
}

/* ============================================================
   USER ID
   ============================================================ */

function requireUserId(
  value: string
): string {
  const userId =
    value.trim();

  if (!userId) {
    throw new Error(
      'User ID is required.'
    );
  }

  return userId;
}

/* ============================================================
   NORMALIZATION
   ============================================================ */

/**
 * Recovery codes generated by SaMi look like:
 *
 * ABCD-12EF-3456
 *
 * Users may type:
 *
 * ABCD-12EF-3456
 * ABCD 12EF 3456
 * ABCD12EF3456
 *
 * All normalize to:
 *
 * ABCD12EF3456
 */
function normalizeRecoveryCode(
  code: string
): string {
  return code
    .trim()
    .toUpperCase()
    .replace(
      /[\s-]+/g,
      ''
    );
}

function isValidRecoveryCode(
  code: string
): boolean {
  return new RegExp(
    `^[A-F0-9]{${RECOVERY_CODE_NORMALIZED_LENGTH}}$`
  ).test(
    normalizeRecoveryCode(
      code
    )
  );
}

/* ============================================================
   HASHING
   ============================================================ */

/**
 * Current SaMi recovery-code hash.
 *
 * HMAC-SHA256 is preferable to concatenating:
 *
 * code + ':' + pepper
 *
 * because the secret is explicitly used as a cryptographic key.
 */
function hashRecoveryCode(
  code: string
): string {
  const normalized =
    normalizeRecoveryCode(
      code
    );

  const pepper =
    getRecoveryCodePepper();

  return crypto
    .createHmac(
      'sha256',
      pepper
    )
    .update(
      normalized,
      'utf8'
    )
    .digest(
      'hex'
    );
}

/**
 * Compatibility hash for recovery codes created by the older
 * SaMi implementation:
 *
 * SHA256(
 *   normalizedCode + ':' + pepper
 * )
 *
 * New recovery codes are NOT created using this format.
 *
 * This allows an existing recovery code created with the same
 * AUTH_RECOVERY_CODE_PEPPER to remain usable while SaMi moves
 * to HMAC-SHA256.
 */
function hashLegacyRecoveryCode(
  code: string
): string {
  const normalized =
    normalizeRecoveryCode(
      code
    );

  const pepper =
    getRecoveryCodePepper();

  return crypto
    .createHash(
      'sha256'
    )
    .update(
      `${normalized}:${pepper}`,
      'utf8'
    )
    .digest(
      'hex'
    );
}

/* ============================================================
   GENERATE PLAIN RECOVERY CODE
   ============================================================ */

function createPlainRecoveryCode():
  string {
  const raw =
    crypto
      .randomBytes(
        RECOVERY_CODE_BYTES
      )
      .toString(
        'hex'
      )
      .toUpperCase();

  return [
    raw.slice(
      0,
      4
    ),

    raw.slice(
      4,
      8
    ),

    raw.slice(
      8,
      12
    ),
  ].join('-');
}

/* ============================================================
   CREATE / REGENERATE RECOVERY CODES
   ============================================================ */

/**
 * Creates a fresh recovery-code set.
 *
 * IMPORTANT:
 *
 * Existing unused codes are revoked before the new set becomes
 * active.
 *
 * Revocation + insertion happen in ONE PostgreSQL statement so
 * SaMi does not end up with:
 *
 *   old codes revoked
 *   +
 *   new codes missing
 *
 * if the insert fails.
 */
export async function createRecoveryCodes(
  userId: string,
  count =
    DEFAULT_RECOVERY_CODE_COUNT
): Promise<string[]> {
  const normalizedUserId =
    requireUserId(
      userId
    );

  if (
    !Number.isInteger(
      count
    ) ||
    count < 1 ||
    count >
      MAX_RECOVERY_CODE_COUNT
  ) {
    throw new Error(
      `Recovery code count must be between 1 and ${MAX_RECOVERY_CODE_COUNT}.`
    );
  }

  /*
   * Fail before changing the database if the security
   * configuration is incomplete.
   */
  getRecoveryCodePepper();

  const codes =
    Array.from(
      {
        length:
          count,
      },
      () =>
        createPlainRecoveryCode()
    );

  const codeHashes =
    codes.map(
      (code) =>
        hashRecoveryCode(
          code
        )
    );

  const result =
    await queryControl(
      `
        WITH revoked_codes AS (
          UPDATE user_recovery_codes

          SET
            revoked_at = NOW()

          WHERE user_id = $1
            AND used_at IS NULL
            AND revoked_at IS NULL

          RETURNING id
        )

        INSERT INTO user_recovery_codes (
          user_id,
          code_hash
        )

        SELECT
          $1,
          new_code.code_hash

        FROM unnest(
          $2::text[]
        ) AS new_code(
          code_hash
        )

        RETURNING id
      `,
      [
        normalizedUserId,
        codeHashes,
      ]
    );

  if (
    result.rows.length !==
    count
  ) {
    throw new Error(
      'Recovery codes were not created completely.'
    );
  }

  /*
   * These plaintext codes are intentionally returned exactly
   * once so the UI can ask the user to save them.
   *
   * SaMi stores only their hashes.
   */
  return codes;
}

/* ============================================================
   COUNT ACTIVE RECOVERY CODES
   ============================================================ */

export async function countActiveRecoveryCodes(
  userId: string
): Promise<number> {
  const normalizedUserId =
    requireUserId(
      userId
    );

  const result =
    await queryControl(
      `
        SELECT
          COUNT(*)::int AS count

        FROM user_recovery_codes

        WHERE user_id = $1
          AND used_at IS NULL
          AND revoked_at IS NULL
      `,
      [
        normalizedUserId,
      ]
    );

  const count =
    Number(
      result.rows[0]?.count ??
        0
    );

  if (
    !Number.isFinite(
      count
    ) ||
    count < 0
  ) {
    return 0;
  }

  return count;
}

/* ============================================================
   CONSUME RECOVERY CODE
   ============================================================ */

/**
 * Recovery codes are strictly one-time use.
 *
 * This UPDATE is atomic:
 *
 * two concurrent requests cannot successfully consume the same
 * still-unused record twice.
 */
export async function consumeRecoveryCode(
  userId: string,
  code: string
): Promise<boolean> {
  const normalizedUserId =
    requireUserId(
      userId
    );

  if (
    typeof code !==
      'string' ||
    !isValidRecoveryCode(
      code
    )
  ) {
    return false;
  }

  /*
   * Current HMAC hash plus legacy SaMi hash.
   *
   * The legacy candidate lets codes created before this upgrade
   * continue working when they used the same dedicated pepper.
   */
  const currentHash =
    hashRecoveryCode(
      code
    );

  const legacyHash =
    hashLegacyRecoveryCode(
      code
    );

  const candidateHashes =
    currentHash ===
    legacyHash
      ? [
          currentHash,
        ]
      : [
          currentHash,
          legacyHash,
        ];

  const result =
    await queryControl(
      `
        UPDATE user_recovery_codes

        SET
          used_at = NOW()

        WHERE user_id = $1
          AND code_hash =
            ANY(
              $2::text[]
            )
          AND used_at IS NULL
          AND revoked_at IS NULL

        RETURNING id
      `,
      [
        normalizedUserId,
        candidateHashes,
      ]
    );

  return (
    result.rows.length >
    0
  );
}